<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Team-Details" data-toc-modified-id="Team-Details-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Team Details</a></span></li><li><span><a href="#Problem-Statement---Rewrite" data-toc-modified-id="Problem-Statement---Rewrite-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Problem Statement - Rewrite</a></span><ul class="toc-item"><li><span><a href="#Examples" data-toc-modified-id="Examples-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Examples</a></span></li><li><span><a href="#Challenges" data-toc-modified-id="Challenges-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Challenges</a></span></li><li><span><a href="#Data" data-toc-modified-id="Data-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Data</a></span></li></ul></li><li><span><a href="#Import-Packages" data-toc-modified-id="Import-Packages-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Import Packages</a></span></li><li><span><a href="#UDFs" data-toc-modified-id="UDFs-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>UDFs</a></span><ul class="toc-item"><li><span><a href="#Labeled-Data-Specific" data-toc-modified-id="Labeled-Data-Specific-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Labeled Data Specific</a></span></li></ul></li><li><span><a href="#File-Paths" data-toc-modified-id="File-Paths-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>File Paths</a></span></li><li><span><a href="#Data-Files-and-Quick-Peek-In-the-Data" data-toc-modified-id="Data-Files-and-Quick-Peek-In-the-Data-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Data Files and Quick Peek In the Data</a></span><ul class="toc-item"><li><span><a href="#Match-Articles" data-toc-modified-id="Match-Articles-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Match Articles</a></span></li><li><span><a href="#Commentary" data-toc-modified-id="Commentary-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Commentary</a></span></li><li><span><a href="#Player-Data" data-toc-modified-id="Player-Data-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>Player Data</a></span></li><li><span><a href="#Labeled-Data" data-toc-modified-id="Labeled-Data-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>Labeled Data</a></span></li></ul></li><li><span><a href="#Data-Processing-and-Exploratory-Data-Analysis" data-toc-modified-id="Data-Processing-and-Exploratory-Data-Analysis-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Data Processing and Exploratory Data Analysis</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Player-Data" data-toc-modified-id="Player-Data-7.0.1"><span class="toc-item-num">7.0.1&nbsp;&nbsp;</span>Player Data</a></span><ul class="toc-item"><li><span><a href="#Countries---Team-Size" data-toc-modified-id="Countries---Team-Size-7.0.1.1"><span class="toc-item-num">7.0.1.1&nbsp;&nbsp;</span>Countries - Team Size</a></span></li><li><span><a href="#Player-Data---Preprocessing" data-toc-modified-id="Player-Data---Preprocessing-7.0.1.2"><span class="toc-item-num">7.0.1.2&nbsp;&nbsp;</span>Player Data - Preprocessing</a></span></li></ul></li></ul></li><li><span><a href="#Commentary-Data" data-toc-modified-id="Commentary-Data-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Commentary Data</a></span><ul class="toc-item"><li><span><a href="#Team-Records" data-toc-modified-id="Team-Records-7.1.1"><span class="toc-item-num">7.1.1&nbsp;&nbsp;</span>Team Records</a></span></li><li><span><a href="#Match-Results" data-toc-modified-id="Match-Results-7.1.2"><span class="toc-item-num">7.1.2&nbsp;&nbsp;</span>Match Results</a></span></li><li><span><a href="#Batting-Records" data-toc-modified-id="Batting-Records-7.1.3"><span class="toc-item-num">7.1.3&nbsp;&nbsp;</span>Batting Records</a></span></li><li><span><a href="#Bowling-Records" data-toc-modified-id="Bowling-Records-7.1.4"><span class="toc-item-num">7.1.4&nbsp;&nbsp;</span>Bowling Records</a></span></li><li><span><a href="#Records-Dashboard" data-toc-modified-id="Records-Dashboard-7.1.5"><span class="toc-item-num">7.1.5&nbsp;&nbsp;</span>Records Dashboard</a></span></li><li><span><a href="#Commentary-Event-Distribution" data-toc-modified-id="Commentary-Event-Distribution-7.1.6"><span class="toc-item-num">7.1.6&nbsp;&nbsp;</span>Commentary Event Distribution</a></span></li><li><span><a href="#Process-Keywords-(ball,-shot,-fielding,-others)-and-build-Taxonomies" data-toc-modified-id="Process-Keywords-(ball,-shot,-fielding,-others)-and-build-Taxonomies-7.1.7"><span class="toc-item-num">7.1.7&nbsp;&nbsp;</span>Process Keywords (ball, shot, fielding, others) and build Taxonomies</a></span></li><li><span><a href="#Commentary-Line-Length" data-toc-modified-id="Commentary-Line-Length-7.1.8"><span class="toc-item-num">7.1.8&nbsp;&nbsp;</span>Commentary Line Length</a></span></li></ul></li><li><span><a href="#Labeled-Data---Single-Ball-vs-Multi-Ball-Entity" data-toc-modified-id="Labeled-Data---Single-Ball-vs-Multi-Ball-Entity-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Labeled Data - Single Ball vs Multi Ball Entity</a></span></li><li><span><a href="#Train-Test-Split" data-toc-modified-id="Train-Test-Split-7.3"><span class="toc-item-num">7.3&nbsp;&nbsp;</span>Train Test Split</a></span></li><li><span><a href="#Match-Articles" data-toc-modified-id="Match-Articles-7.4"><span class="toc-item-num">7.4&nbsp;&nbsp;</span>Match Articles</a></span><ul class="toc-item"><li><span><a href="#Mention-Dictionary" data-toc-modified-id="Mention-Dictionary-7.4.1"><span class="toc-item-num">7.4.1&nbsp;&nbsp;</span>Mention Dictionary</a></span></li><li><span><a href="#Article---Number-of-Paragraphs-Distribution" data-toc-modified-id="Article---Number-of-Paragraphs-Distribution-7.4.2"><span class="toc-item-num">7.4.2&nbsp;&nbsp;</span>Article - Number of Paragraphs Distribution</a></span></li><li><span><a href="#Article---Number-of-Lines-Distribution" data-toc-modified-id="Article---Number-of-Lines-Distribution-7.4.3"><span class="toc-item-num">7.4.3&nbsp;&nbsp;</span>Article - Number of Lines Distribution</a></span></li></ul></li><li><span><a href="#Labeled-Data-Continued" data-toc-modified-id="Labeled-Data-Continued-7.5"><span class="toc-item-num">7.5&nbsp;&nbsp;</span>Labeled Data Continued</a></span><ul class="toc-item"><li><span><a href="#Linked-Ball-Count-Distribution" data-toc-modified-id="Linked-Ball-Count-Distribution-7.5.1"><span class="toc-item-num">7.5.1&nbsp;&nbsp;</span>Linked Ball Count Distribution</a></span></li><li><span><a href="#Append-Match-Data,-Articles-Data" data-toc-modified-id="Append-Match-Data,-Articles-Data-7.5.2"><span class="toc-item-num">7.5.2&nbsp;&nbsp;</span>Append Match Data, Articles Data</a></span></li><li><span><a href="#Feature:-Mention-Text-Length" data-toc-modified-id="Feature:-Mention-Text-Length-7.5.3"><span class="toc-item-num">7.5.3&nbsp;&nbsp;</span>Feature: Mention Text Length</a></span></li><li><span><a href="#Feature:-Mention-Text-Contains-Number(s)" data-toc-modified-id="Feature:-Mention-Text-Contains-Number(s)-7.5.4"><span class="toc-item-num">7.5.4&nbsp;&nbsp;</span>Feature: Mention Text Contains Number(s)</a></span></li><li><span><a href="#Identify-Country-and-Player-Names-in-Mention-Text" data-toc-modified-id="Identify-Country-and-Player-Names-in-Mention-Text-7.5.5"><span class="toc-item-num">7.5.5&nbsp;&nbsp;</span>Identify Country and Player Names in Mention Text</a></span><ul class="toc-item"><li><span><a href="#Example-Mention-Text:-has-player-pronoun-but-not-player-name" data-toc-modified-id="Example-Mention-Text:-has-player-pronoun-but-not-player-name-7.5.5.1"><span class="toc-item-num">7.5.5.1&nbsp;&nbsp;</span>Example Mention Text: has player pronoun but not player name</a></span></li><li><span><a href="#Example-Mention-Text:-has-country-pronoun-but-not-country-name" data-toc-modified-id="Example-Mention-Text:-has-country-pronoun-but-not-country-name-7.5.5.2"><span class="toc-item-num">7.5.5.2&nbsp;&nbsp;</span>Example Mention Text: has country pronoun but not country name</a></span></li></ul></li></ul></li></ul></li></ul></div>

# Team Details
<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width=569
 style='width:427.0pt;border-collapse:collapse'>
 <tr style='height:16.0pt'>
  <td width=195 nowrap valign=bottom style='width:146.0pt;border:solid #8EA9DB 1.0pt;
  border-right:none;background:#4472C4;padding:0cm 5.4pt 0cm 5.4pt;height:16.0pt'>
  <p class=MsoNormal><b><span style='color:white'>Name</span></b></p>
  </td>
  <td width=87 nowrap valign=bottom style='width:65.0pt;border-top:solid #8EA9DB 1.0pt;
  border-left:none;border-bottom:solid #8EA9DB 1.0pt;border-right:none;
  background:#4472C4;padding:0cm 5.4pt 0cm 5.4pt;height:16.0pt'>
  <p class=MsoNormal><b><span style='color:white'>PGID</span></b></p>
  </td>
  <td width=288 nowrap valign=bottom style='width:216.0pt;border:solid #8EA9DB 1.0pt;
  border-left:none;background:#4472C4;padding:0cm 5.4pt 0cm 5.4pt;height:16.0pt'>
  <p class=MsoNormal><b><span style='color:white'>Email</span></b></p>
  </td>
 </tr>
 <tr style='height:16.0pt'>
  <td width=195 nowrap valign=bottom style='width:146.0pt;border-top:none;
  border-left:solid #8EA9DB 1.0pt;border-bottom:solid #8EA9DB 1.0pt;border-right:
  none;background:#D9E1F2;padding:0cm 5.4pt 0cm 5.4pt;height:16.0pt'>
  <p class=MsoNormal><span style='font-family:"Helvetica Neue";color:black'>Aejaz&nbsp;Mohammad&nbsp;Pamidi</span></p>
  </td>
  <td width=87 nowrap valign=bottom style='width:65.0pt;border:none;border-bottom:
  solid #8EA9DB 1.0pt;background:#D9E1F2;padding:0cm 5.4pt 0cm 5.4pt;
  height:16.0pt'>
  <p class=MsoNormal align=right style='text-align:right'><span
  style='font-family:"Helvetica Neue";color:black'>11920026</span></p>
  </td>
  <td width=288 nowrap valign=bottom style='width:216.0pt;border-top:none;
  border-left:none;border-bottom:solid #8EA9DB 1.0pt;border-right:solid #8EA9DB 1.0pt;
  background:#D9E1F2;padding:0cm 5.4pt 0cm 5.4pt;height:16.0pt'>
  <p class=MsoNormal><span style='color:black'>aejazmohammad_ampba2020w@isb.edu</span></p>
  </td>
 </tr>
 <tr style='height:16.0pt'>
  <td width=195 nowrap valign=bottom style='width:146.0pt;border-top:none;
  border-left:solid #8EA9DB 1.0pt;border-bottom:solid #8EA9DB 1.0pt;border-right:
  none;padding:0cm 5.4pt 0cm 5.4pt;height:16.0pt'>
  <p class=MsoNormal><span style='font-family:"Helvetica Neue";color:black'>Bharat
  Bhushan Joshi</span></p>
  </td>
  <td width=87 nowrap valign=bottom style='width:65.0pt;border:none;border-bottom:
  solid #8EA9DB 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;height:16.0pt'>
  <p class=MsoNormal align=right style='text-align:right'><span
  style='font-family:"Helvetica Neue";color:black'>11920074</span></p>
  </td>
  <td width=288 nowrap valign=bottom style='width:216.0pt;border-top:none;
  border-left:none;border-bottom:solid #8EA9DB 1.0pt;border-right:solid #8EA9DB 1.0pt;
  padding:0cm 5.4pt 0cm 5.4pt;height:16.0pt'>
  <p class=MsoNormal><span style='color:black'>bharatbhushan_ampba2020w@isb.edu</span></p>
  </td>
 </tr>
 <tr style='height:16.0pt'>
  <td width=195 nowrap valign=bottom style='width:146.0pt;border-top:none;
  border-left:solid #8EA9DB 1.0pt;border-bottom:solid #8EA9DB 1.0pt;border-right:
  none;background:#D9E1F2;padding:0cm 5.4pt 0cm 5.4pt;height:16.0pt'>
  <p class=MsoNormal><span style='font-family:"Helvetica Neue";color:black'>Ganesh&nbsp;Belde</span></p>
  </td>
  <td width=87 nowrap valign=bottom style='width:65.0pt;border:none;border-bottom:
  solid #8EA9DB 1.0pt;background:#D9E1F2;padding:0cm 5.4pt 0cm 5.4pt;
  height:16.0pt'>
  <p class=MsoNormal align=right style='text-align:right'><span
  style='font-family:"Helvetica Neue";color:black'>11920089</span></p>
  </td>
  <td width=288 nowrap valign=bottom style='width:216.0pt;border-top:none;
  border-left:none;border-bottom:solid #8EA9DB 1.0pt;border-right:solid #8EA9DB 1.0pt;
  background:#D9E1F2;padding:0cm 5.4pt 0cm 5.4pt;height:16.0pt'>
  <p class=MsoNormal><span style='color:black'>ganesh_belde_ampba2020w@isb.edu</span></p>
  </td>
 </tr>
 <tr style='height:16.0pt'>
  <td width=195 nowrap valign=bottom style='width:146.0pt;border-top:none;
  border-left:solid #8EA9DB 1.0pt;border-bottom:solid #8EA9DB 1.0pt;border-right:
  none;padding:0cm 5.4pt 0cm 5.4pt;height:16.0pt'>
  <p class=MsoNormal><span style='font-family:"Helvetica Neue";color:black'>Kalyan
  Sagar</span></p>
  </td>
  <td width=87 nowrap valign=bottom style='width:65.0pt;border:none;border-bottom:
  solid #8EA9DB 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;height:16.0pt'>
  <p class=MsoNormal align=right style='text-align:right'><span
  style='font-family:"Helvetica Neue";color:black'>11920040</span></p>
  </td>
  <td width=288 nowrap valign=bottom style='width:216.0pt;border-top:none;
  border-left:none;border-bottom:solid #8EA9DB 1.0pt;border-right:solid #8EA9DB 1.0pt;
  padding:0cm 5.4pt 0cm 5.4pt;height:16.0pt'>
  <p class=MsoNormal><span style='color:black'>kalyan_sagar_ampba2020w@isb.edu</span></p>
  </td>
 </tr>
 <tr style='height:16.0pt'>
  <td width=195 nowrap valign=bottom style='width:146.0pt;border-top:none;
  border-left:solid #8EA9DB 1.0pt;border-bottom:solid #8EA9DB 1.0pt;border-right:
  none;background:#D9E1F2;padding:0cm 5.4pt 0cm 5.4pt;height:16.0pt'>
  <p class=MsoNormal><span style='font-family:"Helvetica Neue";color:black'>Rajesh
  Reddy&nbsp;Goutha</span></p>
  </td>
  <td width=87 nowrap valign=bottom style='width:65.0pt;border:none;border-bottom:
  solid #8EA9DB 1.0pt;background:#D9E1F2;padding:0cm 5.4pt 0cm 5.4pt;
  height:16.0pt'>
  <p class=MsoNormal align=right style='text-align:right'><span
  style='font-family:"Helvetica Neue";color:black'>11920005</span></p>
  </td>
  <td width=288 nowrap valign=bottom style='width:216.0pt;border-top:none;
  border-left:none;border-bottom:solid #8EA9DB 1.0pt;border-right:solid #8EA9DB 1.0pt;
  background:#D9E1F2;padding:0cm 5.4pt 0cm 5.4pt;height:16.0pt'>
  <p class=MsoNormal><span style='color:black'>rajeshreddy_ampba2020w@isb.edu</span></p>
  </td>
 </tr>
</table>

<img align="left" height="100" alt="Team" src="image_art/mustangs2.png">

# Problem Statement - Rewrite

<div class="alert alert-block alert-danger">
      
- Every game of any sport leads to a temporal data series, e.g., minute-by-minute commentaries of soccer, ball-by-ball commentaries of baseball or cricket, move-by-move commentaries of chess games.
- For each one-day cricket match, online portals publish ball-by-ball commentaries for a maximum of 600 balls (plus the extras) per match. 
- Also, multiple experts write articles (or reports) describing the events that occurred during the match. 
- We focus on providing an ability to the user to zoom in on a particular event mention from a match report, and read the ball commentaries most relevant to the event.
- CricketLinking: Linking Event Mentions from CricketMatch Reports to Ball Entities in Commentaries
</div>    


<div class="alert alert-block alert-danger">
<img src="image_art/p5_img1.png" alt="example" style="float: left;width: 900px;"/>

      
<br>
    
## Examples
- “Ryan Doeschate produced a scintillating 119 from 110 balls” - this phrase should link to the 110 balls.
- “brilliant bowling figures of 2 for 47 in ten overs” - this phrase should link to the 60 balls bowled by the player.
- “a sparky cameo of 29 from 25 balls” - this phrase should link to the 25 balls.
- “Harbhajan and Munaf Patel put together a spell of 19 balls for just eight runs” - this phrase should link to the 19 balls.
- “The first 5 wickets fell pretty quickly” - this phrase should link to the 5 balls where the first 5 wickets got out.
- “The India innings” - this phrase should link to all the balls from the India innings
    </div>

<div class="alert alert-block alert-danger">

## Challenges
- Mentions could link to one ball or a set of balls.
- Multi-ball event entities (i.e., the set of balls) do not have a canonical name making the candidate detection - itself quite challenging. Also since there are no well-defined semantic groups of ball entities, potential candidates could be exponentially large in number.
- Cricket reports use a versatile way of representing the game and thus there is a heavy use of synonyms, idioms and writing styles.

## Data
- 30 matches from 2011 Cricket World Cup,187 articles, 14 countries, 207 players, 15718 balls, 2828 labelled mentions.
- matchArticles.txt – match number, article number, title, subtitle, author and location, date, articleText
- matchCommentary.txt – match number, innings number, ball number, country1, country2, winning country, batsman on strike, other batsman, runs, bowler, totalRuns, totalWickets, runrate, required run rate, previous bowler, batsman1 stats, batsman2 stats, bowler stats, event type, was reviewed?, is free hit, ball type, shot type, fielding position, keywords, out player, original commentary line.
- playerURLCountryName.txt has more information about the players.
- LabeledData.xlsx contains labels for 2828 mentions.

</div>


# Import Packages

In [209]:
import pandas as pd
import numpy as np
import re
import collections
from collections import defaultdict
import math
from functools import reduce

#NLP
import spacy
from spacy import displacy
nlp = spacy.load("en_core_web_sm")
from spacy.matcher import Matcher

#Model
from sklearn.model_selection import train_test_split

from IPython.display import IFrame
import plotly.express as px
import plotly.graph_objects as go

# UDFs

In [2]:
def print_full(x):
    pd.set_option('display.max_rows', len(x))
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', 3000)
    pd.set_option('display.float_format', '{:20,.2f}'.format)
    pd.set_option('display.max_colwidth', None)
    display(x)
    pd.reset_option('display.max_rows')
    pd.reset_option('display.max_columns')
    pd.reset_option('display.width')
    pd.reset_option('display.float_format')
    pd.reset_option('display.max_colwidth')
def print_full1(x):
    pd.set_option('display.max_rows', len(x))
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', 3000)
    pd.set_option('display.float_format', '{:20,.0f}'.format)
    pd.set_option('display.max_colwidth', None)
    display(x)
    pd.reset_option('display.max_rows')
    pd.reset_option('display.max_columns')
    pd.reset_option('display.width')
    pd.reset_option('display.float_format')
    pd.reset_option('display.max_colwidth')    

In [3]:
def split_alias(alias):
    return re.sub('___$','',re.sub('^(.*?)(?:\((.*)\))?$','\\1___\\2',alias)).split('___')
def alias_list_tokenize(name,alias):
    player_stop_words=['ten']
    alias_list=split_alias(alias)
    name_list=[name]+alias_list
    if 'Ryan ten Doeschate' in name_list:
        name_list.append('ten doeschate')
    if 'Sachin Tendulkar' in name_list:
        name_list.append('Master Blaster')
    
    name_list=list(set(name_list))
    name_tokens=[]
    
    name_list=[re.sub(' +',' ',i).strip() for i in name_list]
    for name in name_list:
        for token in re.split('-| ',name):
            if len(token)>1 and token not in name_tokens and token not in player_stop_words:
                name_tokens.append(token)
    name_list = sorted(name_list, key=len,reverse=True) 
    name_tokens = sorted(name_tokens, key=len,reverse=True) 
    return name_list,name_tokens
# #testcase
# i=146
# name=df_player.iloc[i]['name']
# alias=df_player.iloc[i]['name_aliases']
# print('Name: %s'%name)
# print('Alias: %s'%alias)
# name_obj=alias_list_tokenize(name,alias)
# print('Multi-grams: %s'%name_obj[0])
# print('Uni-grams: %s'%name_obj[1])

In [4]:
### Identify Country on strike
def batting_country(row):
    #print(row)
    player_country = df_player.loc[df_player['name']==row['batsman_on_strike'],'country'].values[0]
    country1 = df_match.loc[df_match['match_number']==row['match_number'],'country1'].values[0]
    country2 = df_match.loc[df_match['match_number']==row['match_number'],'country2'].values[0]
    if(player_country==country1):
        return(country1)
    else:
        return(country2)

def chasing_country(row):
    #print(row)
    player_country = df_player.loc[df_player['name']==row['batsman_on_strike'],'country'].values[0]
    country1 = df_match.loc[df_match['match_number']==row['match_number'],'country1'].values[0]
    country2 = df_match.loc[df_match['match_number']==row['match_number'],'country2'].values[0]
    if(player_country==country1):
        return(country2)
    else:
        return(country1)

def winby_wick_runs(x):
    if(x['winning_country']==x['batting_country']):
        runs = int(abs(x['runs_c1']-x['runs_c2']))
        return(str(runs)+' Runs')
       
    else:
        if str(x['out_c2'])=='nan':
            w=0
        else:
            w=int(abs(10-x['out_c2']))
        wickets = w
        return(str(wickets)+' Wickets')    

def find_overs(x):
    overs = np.floor((x['ball']-x['extra'])/6)
    balls = (x['ball']-x['extra'])%6
    return(str(int(overs))+'.'+str(balls))
    

In [98]:
def get_kw_dict(col):
    list_kw=df_commentary[df_commentary[col].notnull()][col].tolist()
    list_kw=[i.split(';') for i in list_kw]
    dict_kw={}
    for elements in list_kw:
        for element in elements:
            if element!='':
                dict_kw[element]=dict_kw.get(element,0)+1
    return dict_kw,set(dict_kw.keys())
def get_kw_counts(keyword):
    out_dict={}
    out_dict['shot_count']=dict_shot_type.get(keyword,0)
    out_dict['ball_type_count']=dict_ball_type.get(keyword,0)
    out_dict['fielding_position_count']=dict_fielding_position.get(keyword,0)
    out_dict['keywords_count']=dict_keywords.get(keyword,0)
    return out_dict


In [227]:
def def_value(): 
    return {}

def parse_article(article_text):
    #meta=''
    #PAT_META_SPLIT='^(.*?)(#p#.*)$'
    #PAT_META_SPLIT_search = re.search(PAT_META_SPLIT, article_text)
    #meta_text=PAT_META_SPLIT_search.group(1).strip()
    #text=PAT_META_SPLIT_search.group(2).strip()
    #peras=[i.strip() for i in text.split('#p#') if i!='']
    
    peras=[i.strip() for i in article_text.split('#p#') if i!='']
    peras_count=len(peras)
    
    line_num=0
    line_list=[]
    line_list_text=[]
    for pera_num, pera_text in enumerate(peras):
        pera_num=pera_num+1
        para_segments=[i.strip() for i in re.split('\(|\)',pera_text)]
        for segment in para_segments:
            #segment=re.sub('</?m[0-9]+>','',segment)
            doc = nlp(segment)
            for sent in doc.sents:
                sent_text=sent.text
                if sent_text!='.' or sent_text!='. ':
                    line_list_text.append(sent_text)
        line_list_text[-1]=line_list_text[-1]+'#p#'
    test_list=line_list_text[0:-1]
    new_test_list=[test_list[0]]
    for i in range(1,len(test_list)):
        if test_list[i]=='>' or test_list[i]=='>,' or test_list[i]=='>.':
            new_test_list[-1]=new_test_list[-1]+test_list[i]
        else:
            new_test_list.append(test_list[i])
    test_list=new_test_list
    for i in range(0,10):
        new_test_list=[test_list[0]]
        for i in range(1,len(test_list)):
            PAT_MENTION_ID_end='</m([0-9]+)>?'
            PAT_MENTION_ID_end_search = re.search(PAT_MENTION_ID_end, test_list[i])
            if PAT_MENTION_ID_end_search:
                m_no=PAT_MENTION_ID_end_search.group(1)
                PAT_MENTION_ID_start='<m{}>'.format(m_no)
                PAT_MENTION_ID_start_search = re.search(PAT_MENTION_ID_start, test_list[i])
                if not PAT_MENTION_ID_start_search:
                    new_test_list[-1]=new_test_list[-1]+test_list[i]
                else:
                    new_test_list.append(test_list[i])
            else:
                new_test_list.append(test_list[i])
        test_list=new_test_list
    #for element in test_list:
    #    print(element)
    test_list=[i.strip() for i in test_list if i not in ['','>']]
    new_test_list=[]
    for i in test_list:
        i=re.sub('^(>|,)* ?','',i)
        i=re.sub('^\.#p#','#p#',i)
        PAT_MENTION_ID_incomplete = re.search('(</m[0-9]+)$', i) 
        if PAT_MENTION_ID_incomplete:
            i=re.sub('(</m[0-9]+)$',PAT_MENTION_ID_incomplete.group(1)+'>',i)
        new_test_list.append(i)
    
    line_list_text=new_test_list 
    
    pera_num=1
    line_num=1
    line_list=[]
    new_line_list=[]
    for i in line_list_text:
        if '#p#' in i:
            pera_num=pera_num+1
            i=re.sub('#p#','',i)
        if i!='':
            mention_ids=re.findall('<m[0-9]+>?',i)
            mention_ids=[re.sub('(<m|>)','',i) for i in mention_ids]
            #print(i,mention_ids)
            line_list.append([pera_num,line_num,i,mention_ids])    
            line_num=line_num+1
            new_line_list.append(i)
    new_line_list=[line_list[0]+['']]
    #print(line_list_text)
    
    for i in range(1,len(line_list)):
        if line_list[i-1][2]!='':
            new_line_list.append(line_list[i]+[line_list[i-1][2]])
        else:
            if line_list[i-2][2]!='':
                new_line_list.append(line_list[i]+[line_list[i-2][2]])
    #line_list_text=new_line_list        
    out_dict={}
    #out_dict['meta_text']=meta_text
    out_dict['peras_count']=pera_num
    out_dict['line_count']=len(line_list_text)
    out_dict['line_list']=new_line_list
    #out_dict['line_list_text']=line_list_text
    return out_dict
##testcase
# i=6
# df_match_articles.iloc[i]['article_text']
# test_list=parse_article(df_match_articles.iloc[i]['article_text'])
# df_match_articles.iloc[i]['article_number']
# test_list

## Labeled Data Specific

In [267]:
taxonomy_player_pronoun_list=['he','his','him','my','i']
taxonomy_country_pronoun_list=['they']
taxonomy_pronoun_list=taxonomy_player_pronoun_list+taxonomy_country_pronoun_list
def get_tags(doc):
    token_list=[]
    token_pos_list=[]
    token_dict={}
    token_str=''
    token_dep_list=[]
    pronoun_count=0
    pronoun_list=[]
    player_pronoun_list=[]
    country_pronoun_list=[]
    
    for token in doc:
        token_lower=token.text.lower()
        token_list.append(token.text)
        token_pos_list.append(token.pos_)
        if (token.pos_=='PRON'or token_lower in taxonomy_pronoun_list) and token.text.lower() not in pronoun_list:
            pronoun_list.append(token.text.lower())
            if token.text.lower() in taxonomy_player_pronoun_list and token.text.lower() not in player_pronoun_list:
                player_pronoun_list.append(token.text.lower())
            if token.text.lower() in taxonomy_country_pronoun_list and token.text.lower() not in country_pronoun_list:
                country_pronoun_list.append(token.text.lower())
                
        token_dep_list.append(token.dep_)
        token_dict[token]=token_dict.get(token,'')+token.dep_
    pronoun_count=len(pronoun_list)
    player_pronoun_count=len(player_pronoun_list)
    country_pronoun_count=len(country_pronoun_list)
    out_dict={}
    out_dict['token_list']=token_list
    out_dict['token_pos_list']=token_pos_list
    out_dict['token_dep_list']=token_dep_list
    out_dict['token_dict']=token_dict
    out_dict['pronoun_count']=pronoun_count
    out_dict['pronoun_list']=pronoun_list    
    out_dict['player_pronoun_count']=player_pronoun_count
    out_dict['player_pronoun_list']=player_pronoun_list
    out_dict['country_pronoun_count']=country_pronoun_count
    out_dict['country_pronoun_list']=country_pronoun_list
    return out_dict
# i=6
# tagged_mention_text1=nlp(train_data1.iloc[i]['mention_text'])
# get_tags(tagged_mention_text1)['player_pronoun_count']

pattern_replacement=[]
pattern_replacement.append(['asking-rate','REQUIREDRATE'])
pattern_replacement.append(['ASKINGRATE','REQUIREDRATE'])
pattern_replacement.append(['asking rate','REQUIREDRATE'])
pattern_replacement.append(['required-rate','REQUIREDRATE'])
pattern_replacement.append(['required rate','REQUIREDRATE'])
pattern_replacement.append(['half-century','HALFCENTURY'])
pattern_replacement.append(['run-out','RUNOUT'])
pattern_replacement.append(['run out','RUNOUT'])
pattern_replacement.append(['all-out','ALLOUT'])
pattern_replacement.append(['all out','ALLOUT'])
pattern_replacement.append(['bowled out','ALLOUT'])
pattern_replacement.append(['stepped out','STEPPEDOUT'])
pattern_replacement.append(['came out','CAMEOUT'])
pattern_replacement.append(['not out','NOTOUT'])
pattern_replacement.append(['not-out','NOTOUT'])
pattern_replacement.append(['played out','PLAYEDOUT'])
pattern_replacement.append(['pulling out','PULLINGOUT'])
pattern_replacement.append(['batted out','BATTEDOUT'])
pattern_replacement.append(['spilled out','SPILLEDOUT'])
pattern_replacement.append(['walked out','WALKEDOUT'])
pattern_replacement.append(['get out','GETOUT'])
pattern_replacement.append(['lash out','LASHOUT'])
pattern_replacement.append(['leave out','LEAVEOUT'])
pattern_replacement.append(['take out','TAKEOUT'])
pattern_replacement.append(['miles out','MILESOUT'])
pattern_replacement.append(['wrists out','WRISTSSOUT'])
pattern_replacement.append(['shot out','SHOTSOUT'])

def norm_mention_text(mention_text):
    for pattern, replacement in pattern_replacement:
        PAT_KW='(?i)(?:^|[^a-z])({})(?:[^a-z]|$)'.format(pattern)
        PAT_KW_search = re.search(PAT_KW, mention_text)
        if PAT_KW_search:
            mention_text=re.sub(pattern,replacement,mention_text,flags=re.IGNORECASE)
    return mention_text
#norm_mention_text("the second miss, off the bowling of Abdur Rehman again, was a true Akmal clanger; Sangakkara was miles out, the ball wasn't even that far down the leg-side and Akmal knocked the bails off swiftly enough. He just didn't have the ball with him.")

In [274]:
def country_player_identification(mention_text,country1,country2):
    contains_country1=contains_country2=0
    contains_country1_player=contains_country2_player=0
    maching_name_grams=[]
    c1_player_ids=[]
    c2_player_ids=[]
    name_list=[j[0] for j in [i.split('__') for i in list(dict_players_name.keys())] if j[1]==country1.lower()]
    name_list=name_list+[j[0] for j in [i.split('__') for i in list(dict_players_name.keys())] if j[1]==country2.lower()]
    name_list=sorted(name_list, key=len,reverse=True) 
    name_token_list=[j[0] for j in [i.split('__') for i in list(dict_players_name_token.keys())] if j[1]==country1.lower()]
    name_token_list=name_token_list+[j[0] for j in [i.split('__') for i in list(dict_players_name_token.keys())] if j[1]==country2.lower()]
    name_token_list=sorted(name_token_list, key=len,reverse=True) 
    
    for name in name_list:
        pat='(?i)(^| )'+name+'([: \',.]|$)'
        if re.search(pat,mention_text):
            has_player_name=1
            maching_name_grams.append(name)
            c1_player_id=dict_players_name.get(name+'__'+country1.lower(),'UN')
            if c1_player_id!='UN':
                country_name=country1.lower()
                country=1
                contains_country1_player=1
                c1_player_ids.append(c1_player_id)
                replacement='<<C'+str(country)+'P'+c1_player_id+'>>'
                mention_text=re.sub(name,replacement,mention_text,flags=re.IGNORECASE)
            c2_player_id=dict_players_name.get(name+'__'+country2.lower(),'UN')
            if c2_player_id!='UN':
                country_name=country2.lower()
                country=2
                contains_country2_player=1
                c2_player_ids.append(c2_player_id)
                replacement='<<C'+str(country)+'P'+c2_player_id+'>>'
                mention_text=re.sub(name,replacement,mention_text,flags=re.IGNORECASE)
    for name in name_token_list:
        pat='(^| )'+name+'([: \',.]|$)'
        if re.search(pat,mention_text):
            has_player_name=1
            maching_name_grams.append(name)
            c1_player_id=dict_players_name_token.get(name+'__'+country1.lower(),'UN')
            #correffrance example i=1086
            if c1_player_id!='UN' and ('_' not in c1_player_id or not(c1_player_id.split('_')[0] in c1_player_ids or c1_player_id.split('_')[1] in c1_player_ids)):
            #if c1_player_id!='UN':
                country_name=country1.lower()
                country=1
                contains_country1_player=1
                c1_player_ids.append(c1_player_id)
                replacement='<<C'+str(country)+'P'+c1_player_id+'>>'
                mention_text=re.sub(name,replacement,mention_text,flags=re.IGNORECASE)
            c2_player_id=dict_players_name_token.get(name+'__'+country2.lower(),'UN')
            if c2_player_id!='UN' and ('_' not in c2_player_id or not(c2_player_id.split('_')[0] in c2_player_ids or c2_player_id.split('_')[1] in c2_player_ids)):
            #if c2_player_id!='UN':
                country_name=country2.lower()
                country=2
                contains_country2_player=1
                c2_player_ids.append(c2_player_id)
                replacement='<<C'+str(country)+'P'+c2_player_id+'>>'
                mention_text=re.sub(name,replacement,mention_text,flags=re.IGNORECASE)
    
    if country1 in mention_text:
        contains_country1=1
        mention_text=re.sub(country1,'<<C1>>',mention_text)
    if country2 in mention_text:
        contains_country2=1
        mention_text=re.sub(country2,'<<C2>>',mention_text)

    c1_player_ids=list(set(c1_player_ids))
    c2_player_ids=list(set(c2_player_ids))
    out_dict={}
    out_dict['mention_text']=mention_text
    out_dict['contains_country1']=contains_country1
    out_dict['contains_country2']=contains_country2
    out_dict['count_country']=contains_country1+contains_country2
    out_dict['contains_country1_player']=contains_country1_player
    out_dict['contains_country2_player']=contains_country2_player
    out_dict['c1_player_ids']=c1_player_ids
    out_dict['c2_player_ids']=c2_player_ids
    out_dict['count_players_country']=contains_country1_player+contains_country2_player
    out_dict['count_players']=len(c1_player_ids)+len(c2_player_ids)
    out_dict['maching_name_grams']=maching_name_grams
    
    
    
    return out_dict

# #testcase
# i=0
# mention_text=train_data1.iloc[i]['canonical_mention_text']
# country1=train_data1.iloc[i]['country1']
# country2=train_data1.iloc[i]['country2']
# print('Mention Text: %s'%mention_text)
# print('Country1: %s'%country1)
# print('Country2: %s'%country2)
# country_player_identification(mention_text,country1,country2)

def get_additional_country_players(mention_text,article_mention_line,article_mention_previous_line,country1,country2):
    mention_dict=country_player_identification(mention_text,country1,country2)
    article_mention_line_dict=country_player_identification(article_mention_line,country1,country2)
    article_mention_previous_line_dict=country_player_identification(article_mention_previous_line,country1,country2)
    out_dict={}
    out_dict['mention_text']=mention_dict['mention_text']
    out_dict['contains_country1']=mention_dict['contains_country1']
    out_dict['contains_country2']=mention_dict['contains_country2']
    out_dict['count_country']=mention_dict['count_country']
    out_dict['contains_country1_player']=mention_dict['contains_country1_player']
    out_dict['contains_country2_player']=mention_dict['contains_country2_player']
    out_dict['c1_player_ids']=mention_dict['c1_player_ids']
    out_dict['c2_player_ids']=mention_dict['c2_player_ids']
    out_dict['count_players_country']=mention_dict['count_players_country']
    out_dict['count_players']=mention_dict['count_players']
    out_dict['maching_name_grams']=mention_dict['maching_name_grams']
    
    additional_contains_country1=0
    additional_contains_country2=0
    additional_c1_player_ids=[]
    additional_c2_player_ids=[]
    
    if mention_dict['contains_country1']==0:
        if article_mention_line_dict['contains_country1']==1:
            additional_contains_country1=1
        else: 
            additional_contains_country1=article_mention_previous_line_dict['contains_country1']
    if mention_dict['contains_country2']==0:
        if article_mention_line_dict['contains_country2']==1:
            additional_contains_country2=1
        else: 
            additional_contains_country2=article_mention_previous_line_dict['contains_country2']
            
    out_dict['additional_contains_country1']=additional_contains_country1
    out_dict['additional_contains_country2']=additional_contains_country2
    out_dict['additional_count_country']=additional_contains_country1+additional_contains_country2
    
    if mention_dict['c1_player_ids']==[]:
        if len(article_mention_line_dict['c1_player_ids'])>0:
            additional_c1_player_ids=article_mention_line_dict['c1_player_ids']
        else: 
            additional_c1_player_ids=article_mention_previous_line_dict['c1_player_ids']
    if mention_dict['c2_player_ids']==[]:
        if len(article_mention_line_dict['c2_player_ids'])>0:
            additional_c2_player_ids=article_mention_line_dict['c2_player_ids']
        else: 
            additional_c2_player_ids=article_mention_previous_line_dict['c2_player_ids']
    if len(additional_c1_player_ids)>0:
        out_dict['additional_contains_country1_player']= 1
    else:
         out_dict['additional_contains_country1_player']=0
    if len(additional_c2_player_ids)>0:    
        out_dict['additional_contains_country2_player']=1
    else:
        out_dict['additional_contains_country2_player']=0
    out_dict['additional_c1_player_ids']=additional_c1_player_ids
    out_dict['additional_c2_player_ids']=additional_c2_player_ids
    out_dict['additional_count_players_country']=out_dict['additional_contains_country1_player']+out_dict['additional_contains_country2_player']
    out_dict['additional_count_players']=len(additional_c1_player_ids)+len(additional_c2_player_ids)
    return out_dict
# #testcase
# i=137
# i=1873
# mention_text=train_data1.iloc[i]['canonical_mention_text']
# article_mention_line=train_data1.iloc[i]['article_mention_line']
# article_mention_previous_line=train_data1.iloc[i]['article_mention_previous_line']
# country1=train_data1.iloc[i]['country1']
# country2=train_data1.iloc[i]['country2']
# print('Mention Text: %s'%mention_text)
# print('article_mention_line: %s'%article_mention_line)
# print('article_mention_previous_line: %s'%article_mention_previous_line)
# print('Country1: %s'%country1)
# print('Country2: %s'%country2)
# get_additional_country_players(mention_text,article_mention_line,article_mention_previous_line,country1,country2)

# File Paths

In [5]:
path_dir='datasets/P5_Cricket_Linking/'
path_labeled_data=path_dir+'LabeledData.xlsx'
file_path_commentry=path_dir+'matchCommentary.txt'
path_match_articles=path_dir+'matchArticles.txt'
path_player_country=path_dir+'playerURLCountryName.txt'

# Data Files and Quick Peek In the Data

## Match Articles

In [6]:
df_match_articles=pd.read_csv(path_match_articles,sep='\t',header=None,names=['match_number','article_number','title','subtitle','author_and_location','date','article_text']) 
print('# Articles: %s'%df_match_articles.shape[0])
print('# Number of Matches: %s'%df_match_articles.match_number.nunique())
print('# Unique Article Numbers: %s'%df_match_articles.article_number.nunique())
print('')
print('Sample Entries')
df_match_articles.sample(5, random_state=10)

# Articles: 544
# Number of Matches: 49
# Unique Article Numbers: 541

Sample Entries


match_number  article_number  \
482            46          508095   
314            31          505984   
383            38          506961   
487            47          508369   
43              5          502518   

                                                 title  \
482  Sri Lanka v England, World Cup 2011, quarter-f...   
314  Australia v Kenya, World Cup 2011, Group A, Ba...   
383  New Zealand v Sri Lanka, Group A, World Cup 20...   
487  Sri Lanka v New Zealand, World Cup 2011, semi-...   
43   England v Netherlands, Group B, World Cup 2011...   

                                        subtitle  \
482           Tharanga and Dilshan crush England   
314  Australia win easily but Kenya regain pride   
383                     Sangakkara takes command   
487  Wright says he likes New Zealand aggression   
43      New highs for Netherlands despite defeat   

                          author_and_location               date  \
482               The Report by Andrew Miller     March 26, 2011   
314            The Report by Andrew McGlashan     March 13, 2011   
383  Nagraj Gollapudi at the Wankhede Stadium     March 18, 2011   
487                        ESPNcricinfo staff     March 28, 2011   
43                                   S Rajesh  February 22, 2011   

                                          article_text  
482  #p#Sri Lanka 231 for 0 (Dilshan 108*, Tharanga...  
314  #p#Australia 324 for 6 (Clarke 93, Hussey 54) ...  
383  Kumar Sangakkara found the perfect balance bet...  
487  John Wright admits that batting well will be k...  
43   The wagon-wheel of boundaries in Netherlands' ...

## Commentary

In [7]:
df_commentary=pd.read_csv(file_path_commentry,sep='\t',header=None,
                          names=['match_number','innings_number','ball_number',
                                 'country1','country2','winning_country','batsman_on_strike',
                                 'other_batsman','runs','bowler','total_runs','total_wickets',
                                 'runrate','required_run_rate','previous_bowler','batsman1_stats',
                                 'batsman2_stats','bowler_stats','event_type','was_reviewed?',
                                 'is_free_hit','ball_type','shot_type','fielding_position',
                                 'keywords','out_player','original_commentary_line'])
print('# Balls: %s'%df_commentary.shape[0])
print('# Matches: %s'%df_commentary.match_number.nunique())
print('# Countries: %s'%len(list(set(df_commentary.country1.unique().tolist()).union(set(df_commentary.country2.unique().tolist())))))
print('')
# print('Columns:')
# print('--------------')
# _ = [print(i) for i in list(df_commentary.columns)]
# print('--------------')
# print('')
print('Sample Entries')
print_full(df_commentary.sample(5, random_state=10))

# Balls: 15718
# Matches: 30
# Countries: 14

Sample Entries


match_number  innings_number ball_number      country1      country2 winning_country batsman_on_strike   other_batsman  runs       bowler  total_runs  total_wickets              runrate    required_run_rate   previous_bowler     batsman1_stats      batsman2_stats bowler_stats event_type  was_reviewed? is_free_hit ball_type shot_type fielding_position                  keywords out_player                                                                                                                                              original_commentary_line
7997             16               1       1.5.0  South Africa   Netherlands    South Africa           HM Amla        GC Smith     0  BA Westdijk           9              0                 4.00                 0.00  Mudassar Bukhari   8* (10b 2x4 0x6)     1* (1b 0x4 0x6)      0-0-5-0        NaN          False         NaN       NaN    block;               NaN  good length;length;line;        NaN                                              Westdijk to Amla, no run, good length around off stump, a hint of away movement, Amla is nicely behind the line to block
11536            23               2      24.5.0         Kenya        Canada          Canada         AS Hansra         A Bagai     2     CO Obuya          99              3                 3.83                 4.11        JK Kamande  28* (50b 4x4 0x6)   17* (34b 1x4 0x6)     1-0-13-0        NaN          False         NaN       NaN       NaN               NaN                 leg side;        NaN                                                                   CO Obuya to Hansra, 2 runs, now he goes down the leg side, and it is ticked fine for another coupls
6411             12               2      29.6.0      Zimbabwe        Canada        Zimbabwe    Khurram Chohan      ZE Surkari     0  SC Williams          80              7                 2.72                10.47         AG Cremer    0* (7b 0x4 0x6)    6* (19b 0x4 0x6)      0-0-1-0        NaN          False         NaN       NaN       NaN               NaN             pitch;defend;        NaN                                                                                     Williams to Khurram Chohan, no run, full, turns away after pitching off, defended
5456             11               1      23.1.1         India       England      Match tied         G Gambhir    SR Tendulkar     0    A Shahzad         132              1                 5.69                 0.00          MH Yardy  39* (45b 4x4 0x6)   53* (69b 3x4 2x6)     3-0-17-0        NaN          False         NaN       NaN       NaN               NaN   crease;line;length;one;        NaN  Shahzad to Gambhir, no run, much better line here - off stump. The length is good too and catches Gambhir on the crease. The defence wasn't certain but no harm done
3601              7               2      39.4.0   West Indies  South Africa    South Africa         JP Duminy  AB de Villiers     1     CH Gayle         208              3                 5.25                 1.63           SJ Benn  33* (41b 1x4 0x6)  101* (98b 8x4 2x6)     4-0-21-0        NaN          False         NaN       NaN       NaN            cover;          covers;ball;one;        NaN                                                                                          Gayle to Duminy, 1 run, JP taps an off stump ball towards the covers for one

## Player Data

In [8]:
df_player=pd.read_csv(path_player_country,sep='\t',header=None,names=['name','cricinfo_link','country','name_aliases'])
print('# Players: %s'%df_player.shape[0])
print('# Countries: %s'%df_player.country.nunique())
print('')
print('Sample Entries')
df_player.sample(5)

# Players: 207
# Countries: 14

Sample Entries


name                                      cricinfo_link  \
113     MH Yardy  http://www.espncricinfo.com/icc_cricket_worldc...   
17   AN Kervezee  http://www.espncricinfo.com/icc_cricket_worldc...   
129  NN Odhiambo  http://www.espncricinfo.com/icc_cricket_worldc...   
117     MJ Prior  http://www.espncricinfo.com/icc_cricket_worldc...   
68       HM Amla  http://www.espncricinfo.com/icc_cricket_worldc...   

          country                     name_aliases  
113       England                    Michael Yardy  
17    Netherlands  Alexei Kervezee (Alex Kervezee)  
129         Kenya                Nehemiah Odhiambo  
117       England                       Matt Prior  
68   South Africa                      Hashim Amla

## Labeled Data

In [9]:
df_labeled_data=pd.read_excel(path_labeled_data) 
df_labeled_data.columns=['match_number','article_number','mention_id','mention_text','linked_balls']
df_labeled_data['mention_text']=df_labeled_data.apply(lambda x: re.sub(' +',' ',x['mention_text']).strip(),axis=1)
print('# Instances: %s'%df_labeled_data.shape[0])
print('# Matches: %s'%df_labeled_data.match_number.nunique())
print('# Articles: %s'%df_labeled_data.article_number.nunique())
print('')
print('Sample Entries')
df_labeled_data.sample(5)

# Instances: 2828
# Matches: 30
# Articles: 187

Sample Entries


match_number  article_number mention_id  \
1185            14          503674        m44   
2400            27          505679         m4   
2139            25          505058         m5   
1774            21          504526         m5   
2064            24          504887        m10   

                                           mention_text  \
1185  Upul Tharanga, who started sedately, then join...   
2400                             West Indies' 142 for 3   
2139  The Dutchman immediately pushed the short fine...   
1774  Broad removed South African's two quicks, Stey...   
2064  30 off the next over from the same end, bowled...   

                                           linked_balls  
1185                           2:6.1.0,2:6.3.1,2:6.6.0,  
2400                                           1:34.5.0  
2139                                            2:1.1.0  
1774                                 2:47.1.0,2:47.4.0,  
2064  1:48.1.0,1:48.2.0,1:48.3.0,1:48.3.1,1:48.4.0,1...

<div class="alert alert-block alert-info">

- Out of 541 unique articles, mention texts are labeled from only 187 articles.
- These 187 articles has coverage for 30 matches
</div>

# Data Processing and Exploratory Data Analysis
- Except Labeled Data We will now do the required preprocessing and do exploratory data analysis for all the files
- For labeled data we need to do a train test split and do the EDA on train part. This will be done in next section

### Player Data

#### Countries - Team Size

In [10]:
df_player_country=df_player.groupby(['country']).agg({'name':'count'}).reset_index().rename(columns={'name':'players'})
df_player_country.sort_values(by=['players'],ascending=[False],inplace=True)
df_player_country

country  players
3        England       17
8    New Zealand       16
12   West Indies       16
2         Canada       15
4          India       15
6          Kenya       15
7    Netherlands       15
10  South Africa       15
11     Sri Lanka       15
13      Zimbabwe       15
1     Bangladesh       14
9       Pakistan       14
5        Ireland       13
0      Australia       12

<div class="alert alert-block alert-info">

- England fielded most players followed by New Zealand
- Australia fielded least number of players followed by Ireland
</div>

#### Player Data - Preprocessing
- In order to do identify player names from the mention text we now will generate two player name looup dictionaries
    - Multi-grams dictionary (Player Name Grams: Case Insensitive)
    - Uni-grams dictionary (Player Name Gram: Case Sensitive)
- We will use both player names and player aliases to generate these player lookup dictionary
- For each player we have generated an id
- The dictionary key is string delimited by '_' where the left part is player lookup string and right part is country name
- The dictionary value is the player id (in case multiple, then delimited by '_')

In [11]:
df_player=df_player.reset_index()
df_player['player_id']=df_player['index']+1
df_player.drop(columns=['index'],inplace=True)
df_player['name_obj']=df_player.apply(lambda x:alias_list_tokenize(x['name'],x['name_aliases']),axis=1)
df_player['name_list']=df_player.apply(lambda x:x['name_obj'][0],axis=1)
df_player['name_tokens']=df_player.apply(lambda x:x['name_obj'][1],axis=1)
col_order=['player_id','country','name','name_aliases','name_list','name_tokens']
df_player=df_player[col_order]
print('Player Data Frame: Sample Entries')
df_player.sample(5,random_state=10)

#name
df_player_ids=df_player[['name_list','country','player_id']].explode('name_list')
df_player_ids_grouped=df_player_ids.groupby(['name_list','country']).aggregate({'player_id':lambda x:list(x)}).reset_index()
df_player_ids_grouped['id_count']=df_player_ids_grouped.apply(lambda x: len(x['player_id']),axis=1)
df_player_ids_grouped.columns=['name','country','player_ids_list','id_count']
df_player_ids_grouped['player_ids_str']=df_player_ids_grouped.apply(lambda x: '_'.join([str(i) for i in x['player_ids_list']]),axis=1)
df_player_ids_grouped=df_player_ids_grouped[['name','country','player_ids_str','player_ids_list','id_count']]
df_player_ids_grouped['lookup_key']=df_player_ids_grouped['name'].str.lower()+'__'+df_player_ids_grouped['country'].str.lower()


#name token
df_player_ids_name_token=df_player[['name_tokens','country','player_id']].explode('name_tokens')
df_player_ids_grouped_tokens=df_player_ids_name_token.groupby(['name_tokens','country']).aggregate({'player_id':lambda x:list(x)}).reset_index()
df_player_ids_grouped_tokens['id_count']=df_player_ids_grouped_tokens.apply(lambda x: len(x['player_id']),axis=1)
df_player_ids_grouped_tokens.columns=['name_token','country','player_ids_list','id_count']
df_player_ids_grouped_tokens['player_ids_str']=df_player_ids_grouped_tokens.apply(lambda x: '_'.join([str(i) for i in x['player_ids_list']]),axis=1)
df_player_ids_grouped_tokens=df_player_ids_grouped_tokens[['name_token','country','player_ids_str','player_ids_list','id_count']]
df_player_ids_grouped_tokens['lookup_key']=df_player_ids_grouped_tokens['name_token']+'__'+df_player_ids_grouped_tokens['country'].str.lower()

dict_players_name=dict(df_player_ids_grouped[['lookup_key','player_ids_str']].values.tolist())
dict_players_name_token=dict(df_player_ids_grouped_tokens[['lookup_key','player_ids_str']].values.tolist())

print('Sample Player Name (Multi-gram) Dictionary Entries')
print('---------------------------------------------------')
for k,v in list(dict_players_name.items())[0:4]:
    print('lookup key: %s || lookup value (player_ids): %s'%(k,v))
print('')
print('Sample Player Name (Uni-gram) Dictionary Entries')
print('-------------------------------------------------')
for k,v in list(dict_players_name_token.items())[0:4]:
    print('lookup key: %s || lookup value (player_ids): %s'%(k,v))    

Player Data Frame: Sample Entries


player_id    country           name        name_aliases  \
58         59      India      G Gambhir      Gautam Gambhir   
63         64    England       GP Swann        Graeme Swann   
35         36  Sri Lanka  CK Kapugedera  Chamara Kapugedera   
19         20    Ireland       AR White        Andrew White   
59         60   Zimbabwe        GA Lamb           Greg Lamb   

                              name_list                name_tokens  
58          [Gautam Gambhir, G Gambhir]          [Gambhir, Gautam]  
63             [Graeme Swann, GP Swann]        [Graeme, Swann, GP]  
35  [Chamara Kapugedera, CK Kapugedera]  [Kapugedera, Chamara, CK]  
19             [Andrew White, AR White]        [Andrew, White, AR]  
59                 [Greg Lamb, GA Lamb]           [Lamb, Greg, GA]

Sample Player Name (Multi-gram) Dictionary Entries
---------------------------------------------------
lookup key: a bagai__canada || lookup value (player_ids): 1
lookup key: a nehra__india || lookup value (player_ids): 2
lookup key: a shahzad__england || lookup value (player_ids): 3
lookup key: aa obanda__kenya || lookup value (player_ids): 4

Sample Player Name (Uni-gram) Dictionary Entries
-------------------------------------------------
lookup key: AA__kenya || lookup value (player_ids): 4
lookup key: AB__south africa || lookup value (player_ids): 5
lookup key: AC__ireland || lookup value (player_ids): 9
lookup key: AD__sri lanka || lookup value (player_ids): 10


- We used country as part of the lookup key to avoid ambiguity in case a name or part of name is shared by multiple players like in below example

In [12]:
df_player_ids_grouped_tokens[df_player_ids_grouped_tokens['name_token'].str.contains('Ajmal')]

name_token   country player_ids_str player_ids_list  id_count  \
19      Ajmal   England              3             [3]         1   
20      Ajmal  Pakistan            158           [158]         1   

         lookup_key  
19   Ajmal__england  
20  Ajmal__pakistan

- Even after using country as part of the key few players will have common name tokens (as shown below)
- In such cases the dictionary value has multiple player ids delimited by '_'

In [13]:
df_player_ids_grouped_tokens[df_player_ids_grouped_tokens['id_count']>1].sort_values(by=['id_count'],ascending=[False]).head()

name_token      country player_ids_str player_ids_list  id_count  \
10          AR      Ireland          19_20        [19, 20]         2   
286   McCullum  New Zealand         27_128       [27, 128]         2   
494        Tom  Netherlands        185_188      [185, 188]         2   
447      Singh        India         67_205       [67, 205]         2   
409         SO        Kenya        170_171      [170, 171]         2   

                lookup_key  
10             AR__ireland  
286  McCullum__new zealand  
494       Tom__netherlands  
447           Singh__india  
409              SO__kenya

In [14]:
lookup_key='McCullum__new zealand'
print('Lookup Key: %s || Lookup Value (player_ids): %s'%(lookup_key,dict_players_name_token[lookup_key]))

Lookup Key: McCullum__new zealand || Lookup Value (player_ids): 27_128


In [15]:
df_player[df_player['name'].str.contains('McCullum')].head()

player_id      country         name      name_aliases  \
26          27  New Zealand  BB McCullum  Brendon McCullum   
127        128  New Zealand  NL McCullum   Nathan McCullum   

                           name_list              name_tokens  
26   [Brendon McCullum, BB McCullum]  [McCullum, Brendon, BB]  
127   [Nathan McCullum, NL McCullum]   [McCullum, Nathan, NL]

## Commentary Data

### Team Records 

In [32]:
#Calculate Number of winnings per country
#Identify the Batting Country and Chasing country for each record
#Calculate runs made by each country in each match
#Identify the highest and lowest runs for each country
#Calculate fours, sixes and wickets taken by each country
df_match=df_commentary[['match_number','country1','country2','winning_country']].drop_duplicates().reset_index(drop=True)
countries_matches = df_match.country1.to_list()
countries_matches.extend(df_match.country2)
country_matches = pd.DataFrame.from_dict(collections.Counter(countries_matches), orient='index',columns=['Matches']).reset_index()
country_matches = country_matches.rename(columns = {'index':'Country'})

country_match = pd.merge(country_matches,pd.DataFrame(df_match.winning_country.value_counts().reset_index()),left_on='Country',right_on='index').drop('index',axis=1)
country_match = country_match.rename(columns = {'winning_country':'Wins'})
country_match.sort_values(by=['Wins'],ascending=False,inplace=True)
country_match['Lost'] = country_match['Matches']-country_match['Wins']
### Percentage of Winnings
country_match['Win_Per'] = np.round(country_match['Wins']/country_match['Matches'],2)

df_commentary['batting_country'] = df_commentary.apply(lambda x: batting_country(x),axis=1)
df_commentary['chasing_country'] = df_commentary.apply(lambda x: chasing_country(x),axis=1)

match_country_score = df_commentary.groupby(['match_number',
                                             'batting_country']).agg({'total_runs':'max'}).reset_index()

## Calculate highest score for each country
highest_score = match_country_score.groupby(['batting_country']).agg({'total_runs':'max'}).reset_index()
highest_score = highest_score.rename(columns={'total_runs':'Highest_score'})

## Calculate lowest score for each country
lowest_score = match_country_score.groupby(['batting_country']).agg({'total_runs':'min'}).reset_index()
lowest_score = lowest_score.rename(columns={'total_runs':'Lowest_score'})


## Merge country runs, highest score and lowest score
country_match = pd.merge(country_match,highest_score,left_on='Country',right_on='batting_country',how='left')
country_match = pd.merge(country_match,lowest_score,left_on='Country',right_on='batting_country',how='left')
country_match.drop(columns=['batting_country_x','batting_country_y'],inplace=True)

Country_wise_scores = match_country_score.groupby(['batting_country']).agg({'total_runs':'sum'}).reset_index()
Country_wise_scores = Country_wise_scores.rename(columns={'total_runs':'runs'})

## Calculate avg runs for each country
country_wise_stats = pd.merge(country_match,Country_wise_scores,left_on='Country',right_on='batting_country')
country_wise_stats['Avg_runs'] = country_wise_stats['runs']/country_wise_stats['Matches']

#### Total wickets taken by each country
wickets_each_match = df_commentary.groupby(['chasing_country','match_number']).agg({'total_wickets':'max'}).reset_index()
country_wickets = wickets_each_match.groupby('chasing_country').agg({'total_wickets':'sum'}).reset_index()

country_wise_stats = pd.merge(country_wise_stats,country_wickets,left_on='Country',right_on='chasing_country')
country_wise_stats = country_wise_stats.loc[:,~country_wise_stats.columns.str.contains('_country')] ## REmove duplicate col names

##   Fours by each country
fours_per_country = df_commentary[df_commentary['event_type']=='four'].groupby('batting_country').agg({'event_type':'count'}).reset_index()
fours_per_country = fours_per_country.rename(columns = {'event_type':'fours'})

## 6s by each country
six_per_country = df_commentary[df_commentary['event_type']=='six'].groupby('batting_country').agg({'event_type':'count'}).reset_index()
six_per_country = six_per_country.rename(columns = {'event_type':'six'})

## Merge all the above to country wise stats
country_wise_stats = pd.merge(country_wise_stats,fours_per_country,left_on='Country',right_on='batting_country')
country_wise_stats = pd.merge(country_wise_stats,six_per_country,left_on='Country',right_on='batting_country')
country_wise_stats = country_wise_stats.loc[:,~country_wise_stats.columns.str.contains('_country')] 
country_wise_stats['Boundaries_score'] = country_wise_stats['fours']*4+country_wise_stats['six']*6
country_wise_stats = country_wise_stats.sort_values(by='Wins',ascending=False)
country_wise_stats.columns=['country', 'matches', 'wins', 'losses', 'win%', 'highest_score',
                            'lowest_score', 'runs', 'avg_runs', 'wickets', '4s', '6s','4s_6s_runs']
country_wise_stats['avg_runs']=np.round(country_wise_stats['avg_runs'],1)
country_wise_stats.to_csv('country_wise_stats.csv')
country_wise_stats.head()

country  matches  wins  losses  win%  highest_score  lowest_score  \
0  New Zealand        5     4       1  0.80            358            72   
1        India        5     3       2  0.60            370           191   
2    Sri Lanka        5     3       2  0.60            332           146   
3     Pakistan        4     3       1  0.75            317           184   
4  West Indies        4     3       1  0.75            330            59   

   runs  avg_runs  wickets   4s  6s  4s_6s_runs  
0  1104     220.8       42   96  31         570  
1  1405     281.0       44  134  24         680  
2  1217     243.4       37  129   5         546  
3   970     242.5       36   79   7         358  
4   886     221.5       33   80  20         440

### Match Results

In [238]:
df_match=df_commentary[['match_number','country1','country2','winning_country']].drop_duplicates().reset_index(drop=True)
# Calculate total runs made by country-1 in Innings-1 and country-2 in Innings-2
# Calculate fours, sixes, wickets taken and extras given by each country
runs_pivot = df_commentary.pivot_table('total_runs', ['match_number'], 'innings_number',aggfunc='max').reset_index()

### Group by 
event_type_pivot = df_commentary.groupby(['match_number','innings_number','event_type']).agg({'event_type':'count'}).reset_index(level=[0,1])
event_type_pivot['event'] = event_type_pivot.index
event_type_pivot = event_type_pivot.reset_index(drop=True)
event_type_pivot = event_type_pivot.rename(columns={'event_type':'count','event':'event_type'})
event_type_pivot_2 = event_type_pivot.pivot_table('count', ['match_number','innings_number'], 'event_type',aggfunc='sum').reset_index()
#event_type_pivot_2.head()

## Fours and six
fours_pivot = event_type_pivot_2.pivot_table('four', ['match_number'], 'innings_number',aggfunc='sum').reset_index()
out_pivot = event_type_pivot_2.pivot_table('out', ['match_number'], 'innings_number',aggfunc='sum').reset_index()
six_pivot = event_type_pivot_2.pivot_table('six', ['match_number'], 'innings_number',aggfunc='sum').reset_index()
wide_pivot = event_type_pivot_2.pivot_table('wide',['match_number'],'innings_number',aggfunc='sum').reset_index()

df_match_countries = df_commentary[['match_number','country1','country2','winning_country',
                                   'batting_country','chasing_country']]
df_match_countries = df_match_countries.drop_duplicates(subset=['match_number'])
df_match['runs_c1'] = runs_pivot.iloc[0:][1]
df_match['runs_c2'] = runs_pivot.iloc[0:][2]
df_match['four_c1'] = fours_pivot.iloc[0:][1]
df_match['four_c2'] = fours_pivot.iloc[0:][2]
df_match['six_c1'] = six_pivot.iloc[0:][1]
df_match['six_c2'] = six_pivot.iloc[0:][2]
df_match['out_c1'] = out_pivot.iloc[0:][1]
df_match['out_c2'] = out_pivot.iloc[0:][2]
df_match['wide_c1'] = wide_pivot.iloc[0:][1]
df_match['wide_c2'] = wide_pivot.iloc[0:][2]

df_match_countries = df_commentary[['match_number','country1','country2','winning_country','batting_country','chasing_country']]

df_match_countries = df_match_countries.drop_duplicates(subset=['match_number'])

df_match = pd.merge(df_match,df_match_countries.drop(columns=['country1','country2','winning_country']),on='match_number')
df_match['win_margin'] = df_match.apply(lambda x: winby_wick_runs(x),axis=1)


df_match.rename(columns={'match_number':'match','winning_country':'won_by','out_c1':'w_c1','out_c2':'w_c2'},inplace=True)
cols=['match','country1','country2','chasing_country','won_by','win_margin',
                   'runs_c1', 'runs_c2','w_c1', 'w_c2','four_c1', 'four_c2', 'six_c1', 'six_c2', 
                   'wide_c1','wide_c2']
df_match=df_match[cols]
df_match = df_match.fillna(0)
df_match['runs_c1']=df_match['runs_c1'].astype('int')
df_match['runs_c2']=df_match['runs_c2'].astype('int')
df_match['w_c1']=df_match['w_c1'].astype('int')
df_match['w_c2']=df_match['w_c2'].astype('int')
df_match['four_c1']=df_match['four_c1'].astype('int')
df_match['four_c2']=df_match['four_c2'].astype('int')
df_match['six_c1']=df_match['six_c1'].astype('int')
df_match['six_c2']=df_match['six_c2'].astype('int')
sel_cols=['match','country1','country2','chasing_country','won_by','win_margin',
                   'runs_c1', 'runs_c2','w_c1', 'w_c2','four_c1', 'four_c2', 'six_c1', 'six_c2']
df_match.to_csv('match_stats.csv')
print_full(df_match[sel_cols].head())

match     country1     country2 chasing_country       won_by  win_margin  runs_c1  runs_c2  w_c1  w_c2  four_c1  four_c2  six_c1  six_c2
0      1        India   Bangladesh      Bangladesh        India     87 Runs      370      283     4     9       29       18       7       3
1      2        Kenya  New Zealand     New Zealand  New Zealand  10 Wickets       69       72    10     0        4        9       0       2
2      3    Sri Lanka       Canada          Canada    Sri Lanka    210 Runs      332      122     7    10       33        9       2       2
3      4    Australia     Zimbabwe        Zimbabwe    Australia     91 Runs      262      171     6    10       18       11       3       2
4      5  Netherlands      England         England      England   6 Wickets      292      296     6     4       27       24       3       1

### Batting Records

In [240]:
# Group by 'batsman_on_strike' and 'match_number' to get number of matches played by each player
# Calculate below stats for each batter:
#     total runs 
#     total fours and sixes
#     highest Scores of each player:
#     average score of each batter across the matches
#     total centuries and half centuries by each player across the matches
    
# No of matches by player
batter_matches = df_commentary.groupby(['batsman_on_strike']).agg({'match_number':pd.Series.nunique}).reset_index()
batter_matches.rename(columns={'match_number':'No of Innings'},inplace=True)
batter_matches = pd.merge(batter_matches,df_player,left_on='batsman_on_strike',right_on='name',how='left')
batter_matches = pd.merge(batter_matches,df_commentary.groupby(['batsman_on_strike']).agg({'runs':'sum'}).reset_index(),
                         on='batsman_on_strike',how='left')
## group by match number and batsman on strike for getting different types of events for the player in the match
event_type_pivot_player = df_commentary.groupby(['match_number','batsman_on_strike','event_type']).agg({'event_type':'count'}).reset_index(level=[0,1]).rename(columns={'event_type':'Count'})
event_type_pivot_player['event_type']=event_type_pivot_player.index
player_fours = event_type_pivot_player[event_type_pivot_player['event_type']=='four'].rename(columns={'Count':'Fours'})
player_six = event_type_pivot_player[event_type_pivot_player['event_type']=='six'].rename(columns={'Count':'Sixes'})
batter_matches = pd.merge(batter_matches,player_fours.groupby('batsman_on_strike').agg({'Fours':'sum'}).reset_index(),
                        on='batsman_on_strike',how='left')
batter_matches = pd.merge(batter_matches,player_six.groupby('batsman_on_strike').agg({'Sixes':'sum'}).reset_index(),
                        on='batsman_on_strike',how='left')
## Calculate Highest score in a match
player_match_scores = df_commentary.groupby(['batsman_on_strike','match_number']).agg({'runs':'sum'}).reset_index()
player_high_scores = player_match_scores.groupby(['batsman_on_strike']).agg({'runs':'max'}).reset_index()
player_high_scores = player_high_scores.rename(columns = {'runs':'higest_score'})
player_avg_scores = player_match_scores.groupby(['batsman_on_strike']).agg({'runs':'mean'}).reset_index()
player_avg_scores = player_avg_scores.rename(columns = {'runs':'avg'})

## Merge batter matches, player high scores and avg scores
players_scores = [batter_matches,player_high_scores,player_avg_scores]
batter_matches = reduce(lambda left,right: pd.merge(left,right,on='batsman_on_strike'), players_scores)

#batter_matches = batter_matches.drop(columns=['url'])
batter_stats = df_commentary.groupby(['batsman_on_strike','match_number']).agg({'runs':'sum'}).reset_index()
batter_stats['100s'] = batter_stats['runs'].apply(lambda x: math.floor(x/100))
batter_stats['50s'] = batter_stats['runs'].apply(lambda x: math.floor(x/50))
batter_stats_ms =  batter_stats.groupby('batsman_on_strike').agg({'100s':'sum','50s':'sum'}).reset_index()
batter_matches = pd.merge(batter_matches,batter_stats_ms,on='batsman_on_strike',how='left')
batter_matches = batter_matches[['name','country','No of Innings','runs','higest_score','avg',
                    'Sixes','Fours','100s','50s']]
batter_matches = batter_matches.rename(columns ={'name':'player_name',
                                                'Fours':'4s','Sixes':'6s'})
## Fill 'NaN's with '0'
batter_matches = batter_matches.fillna(0)
batter_matches['6s']=batter_matches['6s'].astype('int')
batter_matches['4s']=batter_matches['6s'].astype('int')
batter_matches.rename(columns={'player_name':'batter','No of Innings':'innings','higest_score':'highest_score'},inplace=True)
batter_matches.to_csv('batter_matches.csv',index=False)
print_full(batter_matches.head())

batter       country  innings  runs  highest_score                  avg  6s  4s  100s  50s
0         A Bagai        Canada        5   190             84                38.00   0   0     0    2
1         A Nehra         India        1     0              0                 0.00   0   0     0    0
2       A Shahzad       England        2     8              7                 4.00   1   1     0    0
3       AA Obanda         Kenya        1     9              9                 9.00   0   0     0    0
4  AB de Villiers  South Africa        4   331            140                82.75   7   7     2    5

### Bowling Records

In [241]:
# Calculate below stats for each bowler
#     total runs given by each bowler across the matches
#     total overs and balls boweled by each bowler
#     number of wickets taken by each bowler 
#     economoy of bowler
#         Total runs / overs
#     average of bowler
#         total runs / total wickets
#     total 4s, 6s and extras given by each player
df_commentary['bol_obj']=df_commentary.apply(lambda x:x['ball_number'].split('.'),axis=1)
df_commentary['over']=df_commentary.apply(lambda x:x['bol_obj'][0],axis=1)
df_commentary['ball']=df_commentary.apply(lambda x:x['bol_obj'][1],axis=1)
df_commentary['extra']=df_commentary.apply(lambda x:x['bol_obj'][2],axis=1)
df_commentary.drop(columns=['bol_obj'],inplace=True)
## Extras over wise
df_commentary['extra'] = pd.to_numeric(df_commentary['extra'], errors='coerce')
# No of matches by player
bowler_matches = df_commentary.groupby(['bowler']).agg({'match_number':pd.Series.nunique,
                                                       'ball':'count','extra':'sum','runs':'sum'}).reset_index().rename(columns={'match_number':'Inns'})
bowler_matches = pd.merge(df_player,bowler_matches,left_on='name',right_on='bowler',how='right')


#bowler_matches['overs'] = np.flo((bowler_matches['ball']-bowler_matches['extra'])/6,2)
bowler_matches['overs'] = bowler_matches.apply( find_overs,axis=1)

bowler_matches['econ'] = bowler_matches.apply(lambda x: np.round(x['runs']/np.float(x['overs']),2),axis=1)

event_type_pivot_bowler = df_commentary.groupby(['match_number','bowler',
                                                 'event_type']).agg({'event_type':'count'}).reset_index(level=[0,1])
event_type_pivot_bowler.rename(columns={'event_type':'Count'},inplace=True)
event_type_pivot_bowler['event_type']=event_type_pivot_bowler.index

event_type_pivot_bowler.reset_index(drop=True,inplace=True)

bowler_event_stats = event_type_pivot_bowler.groupby(['bowler','event_type']).agg({'Count':'sum'}).reset_index(level=[0,1])
bowler_event_stats = bowler_event_stats.pivot_table(values='Count', index=['bowler'], 
                                                    columns="event_type").reset_index()

bowler_event_stats = bowler_event_stats.rename(columns={'out':'wickets'})
bowler_matches = pd.merge(bowler_matches,bowler_event_stats[['bowler','wickets','four','six']],
                       on='bowler',how='left')

### Calculate average for each bowler 
bowler_matches['ave'] = bowler_matches.apply(lambda x: np.round(x['runs']/x['wickets'],2),axis=1)
#bowler_matches = bowler_matches.drop(columns=['player','bowler','ball']).sort_values(by='wickets',ascending=False)
bowler_matches = bowler_matches[['name','country','Inns','overs','runs','wickets','ave',
                    'econ','four','six','extra']].sort_values(by='wickets',ascending=False)

## Rename columns
bowler_matches = bowler_matches.rename(columns ={'name':'bolwer','Inns':'innings',
                                               'four':'4s','six':'6s','extra':'extras','ave':'avg'})
bowler_matches = bowler_matches.fillna(0)
bowler_matches['wickets']=bowler_matches['wickets'].astype('int')
bowler_matches['6s']=bowler_matches['6s'].astype('int')
bowler_matches['4s']=bowler_matches['6s'].astype('int')
bowler_matches.to_csv('bowler_matches.csv')
print_full(bowler_matches.head())

bolwer       country  innings overs  runs  wickets                  avg                 econ  4s  6s  extras
102  Shahid Afridi      Pakistan        4  37.5   132       16                 8.25                 3.52   2   2       5
119         Z Khan         India        5  45.4   216       13                16.62                 4.76   1   1       6
37      HS Baidwan        Canada        5  44.4   278       13                21.38                 6.26   5   5       9
39     Imran Tahir  South Africa        3  25.3   100       12                 8.33                 3.95   2   2       3
53       KAJ Roach   West Indies        4  30.3   129       12                10.75                 4.26   0   0       2

### Records Dashboard

In [242]:
IFrame(src='https://cricketlinking.web.app/', width=800, height=600)

### Commentary Event Distribution

In [243]:
df_commentary_event_types=df_commentary.event_type.value_counts(dropna=False).to_frame().reset_index()
df_commentary_event_types.columns=['event','ball_counts']
df_commentary_event_types['percent']=round(df_commentary_event_types['ball_counts']*100/sum(df_commentary_event_types['ball_counts']),2)
df_commentary_event_types.fillna('Missing',inplace=True)
fig = px.bar(df_commentary_event_types,title='Commentary Event Distribution', x='ball_counts',y='event',
             labels={'ball_counts':'Balls', 'event':'Event'},
             hover_data=['ball_counts', 'percent'],color='event',orientation='h',width=800,height=500)
fig.show()

<div class="alert alert-block alert-info">
    
- 84% of the balls are not eventful
- `four` followed by `out` are most common events 
</div>

In [244]:
print('# Total Balls: %s'%df_commentary.shape[0])
print('# Reviewed: %s'%df_commentary[df_commentary['was_reviewed?']==True].shape[0])
print('# Free Hit: %s'%df_commentary[df_commentary['is_free_hit']=='Free Hit'].shape[0])
print('# Commentary line has ball keywords: %s'%df_commentary[df_commentary['ball_type'].notnull()].shape[0])
print('# Commentary line has shot keywords: %s'%df_commentary[df_commentary['shot_type'].notnull()].shape[0])
print('# Commentary line has fielding position keywords: %s'%df_commentary[df_commentary['fielding_position'].notnull()].shape[0])

# Total Balls: 15718
# Reviewed: 103
# Free Hit: 25
# Commentary line has ball keywords: 4391
# Commentary line has shot keywords: 3035
# Commentary line has fielding position keywords: 8376


### Process Keywords (ball, shot, fielding, others) and build Taxonomies
- This taxonomies will be used in mention classification tasks

In [245]:
dict_shot_type,list_shot_type=get_kw_dict('shot_type')
dict_ball_type,list_ball_type=get_kw_dict('ball_type')
dict_fielding_position,list_fielding_position=get_kw_dict('fielding_position')
dict_keywords,list_keywords=get_kw_dict('keywords')

list_keywords_filtered=[]
for i in list(list_keywords):
    if i not in list_shot_type and i not in list_fielding_position and i not in list_ball_type:
        list_keywords_filtered.append(i)
list_keywords_filtered=set(list_keywords_filtered)

print('# Keywords in shot types: %s'%len(list_shot_type))
print('# Keywords in ball types: %s'%len(list_ball_type))
print('# Keywords in fielding positions: %s'%len(list_fielding_position))
print('# Keywords in keywords: %s'%len(list_keywords))
print('# Keywords in keywords filtered: %s'%len(list_keywords_filtered))


# Keywords in shot types: 29
# Keywords in ball types: 25
# Keywords in fielding positions: 37
# Keywords in keywords: 165
# Keywords in keywords filtered: 130


In [246]:
df_ball_kw=pd.DataFrame.from_dict(dict_ball_type, orient='index',columns=['count']).reset_index().rename(columns={'index':'ball'}).sort_values(by=['count'],ascending=False)
df_shot_kw=pd.DataFrame.from_dict(dict_shot_type, orient='index',columns=['count']).reset_index().rename(columns={'index':'shot'}).sort_values(by=['count'],ascending=False)
df_field_kw=pd.DataFrame.from_dict(dict_fielding_position, orient='index',columns=['count']).reset_index().rename(columns={'index':'field_position'}).sort_values(by=['count'],ascending=False)
df_kw=pd.DataFrame.from_dict(dict_keywords, orient='index',columns=['count']).reset_index().rename(columns={'index':'kws'}).sort_values(by=['count'],ascending=False)
df_other_kws=df_kw[df_kw['kws'].isin(list_keywords_filtered)].rename(columns={'kws':'other_keywords'})

In [247]:
fig = px.bar(df_ball_kw,title='Commentary Line - Ball Keywords - Distribution', x='ball',y='count',
             labels={'ball':'Ball Keywords', 'count':'Balls Count'},
             color_discrete_sequence=['darkslateblue'],
             #hover_data=['ball_counts', 'percent'],color='event',orientation='h',width=800,height=500
             
            )
fig.show()

fig = px.bar(df_shot_kw,title='Commentary Line - Shot Keywords - Distribution', x='shot',y='count',
             labels={'shot':'Shot Keywords', 'count':'Balls Count'},
             color_discrete_sequence=['orange'],
             #hover_data=['ball_counts', 'percent'],color='event',orientation='h',width=800,height=500
            )
fig.show()

fig = px.bar(df_field_kw,title='Commentary Line - Field Position Keywords - Distribution', x='field_position',y='count',
             labels={'field_position':'Field Position Keywords', 'count':'Balls Count'},
             color_discrete_sequence=['green'],
             #hover_data=['ball_counts', 'percent'],color='event',orientation='h',width=800,height=500
            )
fig.show()


fig = px.bar(df_other_kws.head(40),title='Commentary Line - Other Top 40 Keywords - Distribution', x='other_keywords',y='count',
             labels={'other_keywords':'Other Keywords', 'count':'Balls Count'},
             color_discrete_sequence=['gray'],
             #hover_data=['ball_counts', 'percent'],color='event',orientation='h',width=800,height=500
            )
fig.show()



### Commentary Line Length

In [248]:
df_commentary['commentary_line_length']=df_commentary.apply(lambda x: len(x['original_commentary_line']),axis=1)
df_commentary[['commentary_line_length']].describe()
fig = px.histogram(df_commentary, x="commentary_line_length", 
                   #histnorm='probability',
                   marginal="box",
                   title='Commentary Line Length - Distribution',
                   opacity=0.75,
                   labels={'commentary_line_length':'# Characters'},
                   color_discrete_sequence=['cadetblue']
                  )
fig.layout.yaxis.title.text = 'Balls Count'
fig.show()
#df_commentary.sort_values(by=['commentary_line_length'],ascending=[False]).head(1).original_commentary_line.values[0]

commentary_line_length
count            15718.000000
mean               131.018196
std                 65.634799
min                 21.000000
25%                 91.000000
50%                115.000000
75%                151.750000
max                914.000000

<div class="alert alert-block alert-info">
    
- Average commentary line length is 121 characters, while median length is 115
- Minimum length is 21 characters, while maximum is 914 characters.
</div>

## Labeled Data - Single Ball vs Multi Ball Entity
<div class="alert alert-block alert-info">

- Out of 541 unique articles, mention texts are labeled from only 187 articles.
- These 187 articles has coverage for 30 matches
</div>

In [249]:
df_labeled_data['ball_count']=df_labeled_data.apply(lambda x: len(x['linked_balls'].split(',')),axis=1)
df_labeled_data['entity_is_single_ball']=df_labeled_data.apply(lambda x: 1 if x['ball_count']==1 else 0,axis=1 )
df_labeled_data['entity_type']=df_labeled_data.apply(lambda x: 'Single Ball' if x['ball_count']==1 else 'Multi Balls',axis=1 )
df_entity_type_distribution=df_labeled_data.groupby(['entity_type']).aggregate({'match_number':['count']}).reset_index()
df_entity_type_distribution.columns=['entity_type','count']
df_entity_type_distribution['percent']=round(df_entity_type_distribution['count']*100/df_entity_type_distribution['count'].sum(),2)

df_article_mention_distribution=df_labeled_data.groupby(['article_number']).agg({'match_number':'count'}).reset_index()
df_article_mention_distribution.columns=['article_number','number_of_mentions']
print_full(df_article_mention_distribution['number_of_mentions'].describe())
print('Average Number of Mentions in an Article: %s'%round(df_article_mention_distribution['number_of_mentions'].mean(),2))
print('Median Number of Mentions in an Article: %s'%round(df_article_mention_distribution['number_of_mentions'].median(),2))

print_full(df_entity_type_distribution)
fig = px.histogram(df_article_mention_distribution, x="number_of_mentions", 
                   #histnorm='probability',
                   marginal="box",
                   title='Distribution of Number of Mentions in Articles: Whole Labeled Data',
                   labels={'number_of_mentions':'# Mentions'},
                   color_discrete_sequence=['cadetblue'])
fig.layout.yaxis.title.text = 'Articles Count'
fig.show()

count                 187.00
mean                   15.12
std                    15.36
min                     1.00
25%                     5.00
50%                     8.00
75%                    17.50
max                    66.00
Name: number_of_mentions, dtype: float64

Average Number of Mentions in an Article: 15.12
Median Number of Mentions in an Article: 8.0


entity_type  count              percent
0  Multi Balls   1267                44.80
1  Single Ball   1561                55.20

## Train Test Split
<div class="alert alert-block alert-info">
    
- Now before we do further analysis of labeled data we will split the data in train and test
- As we are hoping to use joint entity linking/context based entity linking we will divide the data into train and test based on article number. This will allow as to retain all the mentioned texts from a article either in train or test.
- There are total 187 articles in the labeled data.
- Lets see if we keep 80% of the random articles in train and 20% of the articles in test, what distribution we will get for entity types (single ball and multi ball) and for number of mentions in articles

</div>



In [250]:
df_articles=df_labeled_data[['article_number']].drop_duplicates()
train_articles,test_articles=train_test_split(df_articles,test_size=0.2, random_state=42)
train_article_ids=train_articles.article_number.values.tolist()
test_articles_ids=test_articles.article_number.values.tolist()
df_labeled_data['set']=df_labeled_data.apply(lambda x: 'train' if x['article_number'] in train_article_ids else 'test',axis=1) 
df_labeled_data_split_entity_type_dist=df_labeled_data.groupby(['set','entity_is_single_ball']).aggregate({'match_number':['count']}).reset_index()
df_labeled_data_split_entity_type_dist.columns=['set','entity_is_single_ball','count']

df_labeled_data_split_entity_type_dist_train=df_labeled_data_split_entity_type_dist[df_labeled_data_split_entity_type_dist['set']=='train'].copy()
df_labeled_data_split_entity_type_dist_train['percent']=round(df_labeled_data_split_entity_type_dist_train['count']*100/df_labeled_data_split_entity_type_dist_train['count'].sum(),2)

df_labeled_data_split_entity_type_dist_test=df_labeled_data_split_entity_type_dist[df_labeled_data_split_entity_type_dist['set']=='test'].copy()
df_labeled_data_split_entity_type_dist_test['percent']=round(df_labeled_data_split_entity_type_dist_test['count']*100/df_labeled_data_split_entity_type_dist_test['count'].sum(),2)
df_article_mention_distribution_train=df_labeled_data[df_labeled_data['set']=='train'].groupby(['article_number']).agg({'match_number':'count'}).reset_index()
df_article_mention_distribution_train.columns=['article_number','number_of_mentions']

df_article_mention_distribution_test=df_labeled_data[df_labeled_data['set']=='test'].groupby(['article_number']).agg({'match_number':'count'}).reset_index()
df_article_mention_distribution_test.columns=['article_number','number_of_mentions']

complete_data_avg_mentions=round(df_article_mention_distribution['number_of_mentions'].mean(),2)
complete_data_median_mentions=round(df_article_mention_distribution['number_of_mentions'].median(),2)

train_data_avg_mentions=round(df_article_mention_distribution_train['number_of_mentions'].mean(),2)
train_data_median_mentions=round(df_article_mention_distribution_train['number_of_mentions'].median(),2)

test_data_avg_mentions=round(df_article_mention_distribution_test['number_of_mentions'].mean(),2)
test_data_median_mentions=round(df_article_mention_distribution_test['number_of_mentions'].median(),2)

complete_data_single_ball_percent=df_entity_type_distribution.loc[1]['percent']
training_data_single_ball_percent=df_labeled_data_split_entity_type_dist_train[df_labeled_data_split_entity_type_dist_train['entity_is_single_ball']==1].percent.values[0]
test_data_single_ball_percent=df_labeled_data_split_entity_type_dist_test[df_labeled_data_split_entity_type_dist_test['entity_is_single_ball']==1].percent.values[0]

data = {'Average of Mention Count':[
    complete_data_avg_mentions, train_data_avg_mentions, test_data_avg_mentions], 
        'Median of Mention Count':[
    complete_data_median_mentions, train_data_median_mentions, test_data_median_mentions],
       '% Single Ball Entities':[
    complete_data_single_ball_percent, training_data_single_ball_percent, test_data_single_ball_percent]
       } 
df_complete_vs_train_vs_test_mention_dist = pd.DataFrame(data, index =['Complete Data', 'Train Data', 'Test Data']) 

print('Number of Articles in Train: %s (%s%%)'%(len(train_article_ids),round(len(train_article_ids)*100/df_articles.shape[0],2)))
print('Number of Articles in Test: %s (%s%%)'%(len(test_articles_ids),round(len(test_articles_ids)*100/df_articles.shape[0],2)))
print('')
print('Distribution Comparison: Complete Labelled Data, Train Data and Test Data')
print_full(df_complete_vs_train_vs_test_mention_dist)
print('')

Number of Articles in Train: 149 (79.68%)
Number of Articles in Test: 38 (20.32%)

Distribution Comparison: Complete Labelled Data, Train Data and Test Data


Average of Mention Count  Median of Mention Count  % Single Ball Entities
Complete Data                     15.12                     8.00                   55.20
Train Data                        15.25                     8.00                   55.11
Test Data                         14.63                     8.50                   55.58

<div class="alert alert-block alert-info">
  
- As we see from the above table the train and test split has similar distribution of 
    - Single vs multi ball events (55%)
    - Average number of mentions from an article (~15)  
    - Median number of mentions from an article (~8)  
- As we achieved similar distribution, freezing the train-test split approach
</dib>

In [251]:
train_data=df_labeled_data[df_labeled_data.set=='train'].copy()
test_data=df_labeled_data[df_labeled_data.set=='test'].copy()

data = {'# Mention Texts':[
    train_data.shape[0], test_data.shape[0]], 
       } 
df_train_test_split_numbers = pd.DataFrame(data, index =['Train Data', 'Test Data']) 

df_train_test_split_numbers['% of Mention Texts']=\
    round(df_train_test_split_numbers\
    ['# Mention Texts']*100/df_train_test_split_numbers['# Mention Texts'].sum(),2)
df_train_test_split_numbers

# Mention Texts  % of Mention Texts
Train Data             2272               80.34
Test Data               556               19.66

## Match Articles

In [252]:
train_data_articles_entity_types=train_data.groupby(['article_number','entity_is_single_ball']).\
aggregate({"match_number": 'count'}).reset_index()
#train_data_articles_entity_types.colums=['article_number','entity_is_single_ball','count']
train_data_articles_entity_types_pivot=pd.pivot_table(train_data, values='match_number', index=['article_number'],
                    columns=['entity_is_single_ball'], aggfunc='count').reset_index()
train_data_articles_entity_types_pivot.columns=['article_number','count_multi_ball','count_single_ball']
train_data_articles_entity_types_pivot.fillna(0,inplace=True)

train_data_articles_entity_types_pivot['entity_total']=train_data_articles_entity_types_pivot['count_multi_ball']+train_data_articles_entity_types_pivot['count_single_ball']
train_data_articles_entity_types_pivot=train_data_articles_entity_types_pivot

train_data_articles_entity_types_pivot['percent_multi_ball']=train_data_articles_entity_types_pivot['count_multi_ball']*100/train_data_articles_entity_types_pivot['entity_total']
train_data_articles_entity_types_pivot['percent_single_ball']=train_data_articles_entity_types_pivot['count_single_ball']*100/train_data_articles_entity_types_pivot['entity_total']
train_data_articles_entity_types_pivot.sort_values(by=['percent_multi_ball'],inplace=True)
train_data_articles_entity_types_pivot=train_data_articles_entity_types_pivot.reset_index(drop=True).reset_index()
train_data_articles_entity_types_pivot['article_s_number']=train_data_articles_entity_types_pivot['index']+1
train_data_articles_entity_types_pivot.drop(columns=['index'],inplace=True)
col_order=['article_s_number','article_number','count_multi_ball', 'count_single_ball',
        'entity_total', 'percent_multi_ball', 'percent_single_ball']
train_data_articles_entity_types_pivot=train_data_articles_entity_types_pivot[col_order]
fig = go.Figure()
for col in list(train_data_articles_entity_types_pivot.columns)[5:]:
    _ = fig.add_trace(go.Bar(
        y=train_data_articles_entity_types_pivot[col],
        x=train_data_articles_entity_types_pivot.article_s_number,
        name=col+" %",

    ))
_ = fig.update_layout(
        yaxis=dict(
        #ticktext=["0%", "20%", "40%", "60%","80%","100%"],
        #tickvals=[0, 20, 40, 60, 80, 100],
        #tickmode="array",
        titlefont=dict(size=15),
    ),
    autosize=False,
    width=800,
    height=600,
    paper_bgcolor='rgba(0,0,0,0)',
    plot_bgcolor='rgba(0,0,0,0)',
    title={
        'text': "Train Articles - % of Single and Multi Ball Entities",
        'y':0.96,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top'},
    barmode='stack')
fig.show()

<div class="alert alert-block alert-info">
  
- As seen from above stacked plot
    - 26 articles have only single ball entities
    - 4 articles have only multi ball entities
    - In other articles mention text have tendency to be either dominated by single ball entities or multi ball entities
- An article writing style and centered topic of the article may be related to type of mentions.
- This skewness might be because of labeling bias or may be there are some latent categories of articles which determines whether they should will dominantly have single ball or multi ball mentions
</div>

In [253]:
df_match_articles_train=df_match_articles[df_match_articles['article_number'].isin(train_article_ids)].reset_index(drop=True).copy()
df_match_articles_test=df_match_articles[df_match_articles['article_number'].isin(test_articles_ids)].reset_index(drop=True).copy()
df_match_articles_train['text_parse_obj']=df_match_articles_train.apply(lambda x:parse_article(x['article_text']),axis=1)
#df_match_articles_train['article_meta_text']=df_match_articles_train.apply(lambda x:x['text_parse_obj']['meta_text'],axis=1)
df_match_articles_train['peras_count']=df_match_articles_train.apply(lambda x:x['text_parse_obj']['peras_count'],axis=1)
df_match_articles_train['line_count']=df_match_articles_train.apply(lambda x:x['text_parse_obj']['line_count'],axis=1)
df_match_articles_train['line_list']=df_match_articles_train.apply(lambda x:x['text_parse_obj']['line_list'],axis=1)
df_match_articles_train.drop(columns=['text_parse_obj'],inplace=True)
df_match_articles_train_lines=df_match_articles_train[['match_number','article_number','line_list']].explode('line_list')
df_match_articles_train_lines['pera_number']=df_match_articles_train_lines.apply(lambda x: x['line_list'][0],axis=1)
df_match_articles_train_lines['line_number']=df_match_articles_train_lines.apply(lambda x: x['line_list'][1],axis=1)
df_match_articles_train_lines['line_text']=df_match_articles_train_lines.apply(lambda x: x['line_list'][2],axis=1)
df_match_articles_train_lines['previous_line_text']=df_match_articles_train_lines.apply(lambda x: x['line_list'][4],axis=1)
df_match_articles_train_lines['mention_ids']=df_match_articles_train_lines.apply(lambda x: x['line_list'][3],axis=1)
df_match_articles_train_lines['mention_count']=df_match_articles_train_lines.apply(lambda x:len(x['mention_ids'])  ,axis=1)
df_match_articles_train_lines.drop(columns=['line_list'],inplace=True)
df_match_articles_train_lines=df_match_articles_train_lines.reset_index(drop=True)

#parsed articles mentions
df_match_articles_train_mentions=df_match_articles_train_lines[df_match_articles_train_lines['mention_count']>0][['match_number','article_number','pera_number','line_number','line_text','previous_line_text','mention_ids']].explode('mention_ids').rename(columns={'mention_ids':'mention_id'})
df_match_articles_train_mentions['mention_key']=df_match_articles_train_mentions.apply(lambda x: str(x['article_number'])+'_'+str(x['mention_id']),axis=1)
df_match_articles_train_mentions=df_match_articles_train_mentions[['match_number','article_number','pera_number','line_number','mention_id','mention_key','line_text','previous_line_text']]
df_match_articles_train_mentions.head()

match_number  article_number  pera_number  line_number mention_id  \
0             1          501845            1            1          1   
1             1          501845            1            2          2   
2             1          501845            1            3          3   
3             1          501845            1            4          4   
4             1          501845            1            5          5   

  mention_key                           line_text  \
0    501845_1            <m1>India 370 for 4</m1>   
1    501845_2                <m2>Sehwag 175</m2>,   
2    501845_3                 <m3>Kohli 100*</m3>   
3    501845_4  beat <m4>Bangladesh 283 for 9</m4>   
4    501845_5                   <m5>Tamim 70</m5>   

                   previous_line_text  
0                                      
1            <m1>India 370 for 4</m1>  
2                <m2>Sehwag 175</m2>,  
3                 <m3>Kohli 100*</m3>  
4  beat <m4>Bangladesh 283 for 9</m4>

### Mention Dictionary
- Parsed articles mentions dict: to be used for getting more context
- key is article number and mention id delimited by '_'
- value is collection having
    - paragraph number
    - line number
    - line text (original article line of a mention)
    - previous line text (original previous article line of a mention)

In [254]:
mention_dict=defaultdict(def_value) 
for k,pera_number,line_number,line_text,previous_line_text in df_match_articles_train_mentions[['mention_key','pera_number','line_number','line_text','previous_line_text']].values.tolist():
    out_dict={}
    out_dict['pera_number']=pera_number
    out_dict['line_number']=line_number
    out_dict['line_text']=line_text
    out_dict['previous_line_text']=previous_line_text
    mention_dict[k]=out_dict

### Article - Number of Paragraphs Distribution
- Articles - Top 5 in term of Paragraph Counts

In [255]:
cols=['match_number', 'article_number', 'title', 'subtitle',
       'author_and_location', 'date', 'peras_count','line_count','article_text']
df_match_articles_train[cols].sort_values(by=['peras_count'],ascending=[False]).head(5)

match_number  article_number  \
57             11          509803   
145            29          505943   
15              5          502448   
54             11          503620   
76             15          504008   

                                                 title  \
57                                                 NaN   
145                                                NaN   
15   England v Netherlands, Group B, World Cup 2011...   
54                                      World Cup 2011   
76   England v Ireland, World Cup 2011, Group B, Ba...   

                                              subtitle  \
57                                In Tendulkar country   
145                                                NaN   
15            England survive ten Doeschate brilliance   
54   Bresnan's brilliance marks return of England's...   
76      England's destiny slipping through their grasp   

             author_and_location               date  peras_count  line_count  \
57               Wright Thompson      April 7, 2011          271        1168   
145             Nikhil Chouguley                NaN           23          55   
15   The Report by Andrew Miller  February 22, 2011           21          71   
54                 Andrew Miller  February 28, 2011           20          59   
76                 Andrew Miller      March 3, 2011           20          75   

                                          article_text  
57   Blanket coverage: nowhere in India can you esc...  
145  Choice of game. A World Cup match featuring tw...  
15   #p#<m1>England 296 for 4</m1> (<m2>Strauss 88<...  
54   Tim Bresnan was superb in a batsman-dominated ...  
76   England run out of ideas in the wake of an Iri...

In [256]:
df_match_articles_train.peras_count.describe()
fig = px.histogram(df_match_articles_train, x="peras_count", 
                   #histnorm='probability',
                   marginal="box",
                   title='Train Aritcles - Distribution of Number of Paragraphs',
                   opacity=0.75,
                   labels={'peras_count':'Count of Paragraphs'},
                   color_discrete_sequence=['cadetblue']
                  )
fig.layout.yaxis.title.text = '# Articles'
fig.show()

count    150.000000
mean      12.993333
std       21.561368
min        4.000000
25%        8.000000
50%       11.000000
75%       14.000000
max      271.000000
Name: peras_count, dtype: float64

<div class="alert alert-block alert-info">
  
- Outlier article number 509803 with 270 paragraphs
- Average number of paragraphs: 12.46
- Median number of paragraphs: 10
- Minimum number of paragraphs: 3
- Maximum number of paragraphs: 270
- Second Maximum number of paragraphs: 22
</div>

### Article - Number of Lines Distribution
- Articles - Top 5 in term of Line Counts

In [257]:
cols=['match_number', 'article_number', 'title', 'subtitle',
       'author_and_location', 'date', 'peras_count','line_count','article_text']
df_match_articles_train[cols].sort_values(by=['line_count'],ascending=[False]).head()

match_number  article_number  \
57             11          509803   
147            30          505917   
112            21          504844   
140            29          505775   
83             16          503954   

                                                 title  \
57                                                 NaN   
147  Canada v New Zealand, World Cup 2011, Group A,...   
112                                                NaN   
140  India v South Africa, Group B, World Cup 2011,...   
83   Netherlands v South Africa, World Cup 2011, Gr...   

                                         subtitle  \
57                           In Tendulkar country   
147            New Zealand ease to 97-run victory   
112                   South Africa's new bogeymen   
140  South Africa prevail in the battle of nerves   
83      All-round South Africa wallop Netherlands   

                author_and_location            date  peras_count  line_count  \
57                  Wright Thompson   April 7, 2011          271        1168   
147  The Bulletin by Liam Brickhill  March 13, 2011           18          93   
112                       Rob Steen   March 9, 2011           13          90   
140    The Bulletin by Sriram Veera  March 12, 2011           18          89   
83       The Report by Nitin Sundar   March 3, 2011           10          87   

                                          article_text  
57   Blanket coverage: nowhere in India can you esc...  
147  #p#<m1>New Zealand 358 for 6</m1> (<m2>McCullu...  
112  James Anderson tormented the South African bat...  
140  #p#<m1>South Africa 300 for 7</m1> (<m2>Kallis...  
83   #p#<m1>South Africa 351 for 5</m1> (<m2>de Vil...

In [258]:
df_match_articles_train.line_count.describe()
fig = px.histogram(df_match_articles_train, x="line_count", 
                   #histnorm='probability',
                   marginal="box",
                   title='Train Aritcles - Distribution of Number of Lines',
                   opacity=0.75,
                   labels={'line_count':'Count of Lines'},
                   color_discrete_sequence=['cadetblue']
                  )
fig.layout.yaxis.title.text = '# Articles'
fig.show()

count     150.000000
mean       56.886667
std        93.186868
min        12.000000
25%        36.000000
50%        47.000000
75%        64.000000
max      1168.000000
Name: line_count, dtype: float64

<div class="alert alert-block alert-info">

- Outlier article number 509803 with 1161 lines
- Average number of lines: 89
- Median number of lines: 43
- Minimum number of lines: 8
- Maximum number of lines: 1161
- Second Maximum number of lines: 135
</div>    

## Labeled Data Continued

### Linked Ball Count Distribution

In [259]:
print('Average Number of Balls: %s'%round(train_data['ball_count'].mean(),2))
print('Median Number of Balls: %s'%train_data['ball_count'].median())
print('Minimum Number of Balls: %s'%train_data['ball_count'].min())
print('Maximum Number of Balls: %s'%train_data['ball_count'].max())

fig = px.histogram(df_labeled_data, x="ball_count", 
                   #histnorm='probability',
                   marginal="box",
                   title='Distribution of Mention Text Ball Counts (Target)',
                   color_discrete_sequence=['cadetblue'])
fig.show()

Average Number of Balls: 24.77
Median Number of Balls: 1.0
Minimum Number of Balls: 1
Maximum Number of Balls: 316


### Append Match Data, Articles Data

In [268]:
train_data1=train_data.merge(df_match,left_on='match_number',right_on='match').drop(columns=['match'])
train_data1['mention_key']=train_data1.apply(lambda x: str(x['article_number'])+'_'+str(x['mention_id'][1:]),axis=1)
train_data1['mention_obj']=train_data1.apply(lambda x: mention_dict[x['mention_key']],axis=1)
train_data1['article_pera_num']=train_data1.apply(lambda x: x['mention_obj']['pera_number'],axis=1)
train_data1['article_line_num']=train_data1.apply(lambda x: x['mention_obj']['line_number'],axis=1)
train_data1['article_mention_line']=train_data1.apply(lambda x: x['mention_obj']['line_text'],axis=1)
train_data1['article_mention_previous_line']=train_data1.apply(lambda x: x['mention_obj']['previous_line_text'],axis=1)
train_data1['doc']=train_data1.apply(lambda x: nlp(x['mention_text']),axis=1)
train_data1['mention_text_length']=train_data1.apply(lambda x: len(x['mention_text']),axis=1)
train_data1['mention_text_contains_number']=\
    train_data1.apply(lambda x: 1 if re.search('[0-9]',x['mention_text']) is not None else 0,axis=1)
train_data1.drop(columns=['mention_obj'],inplace=True)
train_data1['tags']=train_data1.apply(lambda x: get_tags(x['doc']),axis=1)
train_data1['pronoun_count']=train_data1.apply(lambda x: x['tags']['pronoun_count'],axis=1)
train_data1['pronoun_list']=train_data1.apply(lambda x: x['tags']['pronoun_list'],axis=1)
train_data1['player_pronoun_count']=train_data1.apply(lambda x: x['tags']['player_pronoun_count'],axis=1)
train_data1['player_pronoun_list']=train_data1.apply(lambda x: x['tags']['player_pronoun_list'],axis=1)
train_data1['country_pronoun_count']=train_data1.apply(lambda x: x['tags']['country_pronoun_count'],axis=1)
train_data1['country_pronoun_list']=train_data1.apply(lambda x: x['tags']['country_pronoun_list'],axis=1)
train_data1['canonical_mention_text']=train_data1.apply(lambda x: norm_mention_text(x['mention_text']),axis=1)

### Feature: Mention Text Length

In [269]:
train_data1_mention_text_len_summary=train_data1.groupby(['entity_type']).agg({'mention_text_length':['min',lambda x: np.percentile(x, 25),'mean','median',lambda x: np.percentile(x, 75),'max',lambda x: np.std(x)]})
train_data1_mention_text_len_summary.columns=['Min','25th Percentile','Mean','Median','75th Percentile','Max','SD']
print_full(train_data1_mention_text_len_summary)
fig = px.histogram(train_data1, x="mention_text_length", 
                   histnorm='probability',
                   marginal="box",
                   title='Distribution of Mention Text Length for Entity Types',
                   color="entity_type",
                   opacity=0.75,
                   labels={'mention_text_length':'Mention Text Length'}
                   #color_discrete_sequence=['cadetblue']
                  )
fig.layout.yaxis.title.text = 'Probability'
fig.show()

Min  25th Percentile                 Mean  Median  75th Percentile  Max                   SD
entity_type                                                                                              
Multi Balls    3               21                52.73      43               69  580                47.64
Single Ball    5               25                76.91      50               93  866                88.48

<div class="alert alert-block alert-info">
- As we see from above summary statistics and histograms, for both the entity types mention text is right skewed with long tail on the right side
- Average and median of mention text length is lower for multi ball mention texts
</div>

### Feature: Mention Text Contains Number(s)

In [273]:
train_data1_entity_type_vs_contains_number=pd.pivot_table(
    train_data1, values='match_number', index=['entity_type'],
    columns=['mention_text_contains_number'], aggfunc='count')
train_data1_entity_type_vs_contains_number.columns=['Mention Text: Has No Number','Mention Text: Contains Number']
print_full(train_data1_entity_type_vs_contains_number)    
df_phrase_number_no_number=train_data1.groupby(['mention_text_contains_number']).aggregate({'ball_count':['count','mean']}).reset_index()
df_phrase_number_no_number.columns=['mention_text_contains_number','phrase_count','avg_ball_count']
df_phrase_number_no_number['avg_ball_count']=round(df_phrase_number_no_number['avg_ball_count'],2)
df_phrase_number_no_number['phrase_percent']=round(df_phrase_number_no_number['phrase_count']*100/sum(df_phrase_number_no_number['phrase_count']),2)
df_phrase_number_no_number=df_phrase_number_no_number[['mention_text_contains_number','phrase_count','phrase_percent','avg_ball_count']]
print_full(df_phrase_number_no_number)

Mention Text: Has No Number  Mention Text: Contains Number
entity_type                                                            
Multi Balls                          463                            557
Single Ball                          766                            486

mention_text_contains_number  phrase_count       phrase_percent       avg_ball_count
0                             0          1229                54.09                18.15
1                             1          1043                45.91                32.56

### Identify Country and Player Names in Mention Text

In [278]:
train_data1['tagged_mention_text_obj']=train_data1.apply(
    lambda x: get_additional_country_players(x['canonical_mention_text'],x['article_mention_line'],x['article_mention_previous_line'],x['country1'],x['country2']),axis=1)
train_data1['tagged_mention_text']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['mention_text'],axis=1)
train_data1['count_country']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['count_country'],axis=1)
train_data1['count_players']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['count_players'],axis=1)
train_data1['count_players_country']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['count_players_country'],axis=1)
train_data1['contains_country1']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['contains_country1'],axis=1)
train_data1['contains_country2']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['contains_country2'],axis=1)
train_data1['contains_country1_player']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['contains_country1_player'],axis=1)
train_data1['contains_country2_player']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['contains_country2_player'],axis=1)
train_data1['player_name']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['maching_name_grams'],axis=1)
train_data1['c1_player_ids']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['c1_player_ids'],axis=1)
train_data1['c2_player_ids']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['c2_player_ids'],axis=1)

train_data1['add_count_country']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['additional_count_country'],axis=1)
train_data1['add_count_players']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['additional_count_players'],axis=1)
train_data1['add_count_players_country']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['additional_count_players_country'],axis=1)
train_data1['add_contains_country1']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['additional_contains_country1'],axis=1)
train_data1['add_contains_country2']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['additional_contains_country2'],axis=1)
train_data1['add_contains_country1_player']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['additional_contains_country1_player'],axis=1)
train_data1['add_contains_country2_player']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['additional_contains_country2_player'],axis=1)
#train_data1['add_maching_name_grams']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['additional_maching_name_grams'],axis=1)
train_data1['add_c1_player_ids']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['additional_c1_player_ids'],axis=1)
train_data1['add_c2_player_ids']=train_data1.apply(lambda x: x['tagged_mention_text_obj']['additional_c2_player_ids'],axis=1)
train_data1.drop(columns=['tagged_mention_text_obj'],inplace=True)

col_order=['match_number','country1', 'country2', 'won_by',
           'mention_key', 'mention_text','canonical_mention_text','tagged_mention_text','count_country','add_count_country', 'count_players','add_count_players', 'count_players_country',
           'article_mention_line','article_mention_previous_line',
           'entity_is_single_ball','player_pronoun_count','player_pronoun_list','country_pronoun_count','country_pronoun_list','pronoun_count','pronoun_list']

In [279]:
print_full(train_data1[col_order].sample(10))

match_number     country1      country2        won_by mention_key                                                                                                                                                     mention_text                                                                                                                                           canonical_mention_text                                                                                                                                         tagged_mention_text  count_country  add_count_country  count_players  add_count_players  count_players_country                                                                                                                                                      article_mention_line                                                                                                                                                                                                     article_mention_previous_line  entity_is_single_ball  player_pronoun_count player_pronoun_list  country_pronoun_count country_pronoun_list  pronoun_count pronoun_list
926             13  West Indies   Netherlands   West Indies    503653_3                                                                                                                                                      six wickets                                                                                                                                                      six wickets                                                                                                                                                 six wickets              0                  1              0                  1                      0                                                   and <m3>six wickets</m3>, was the bowling star, but you would have to think that West Indies would have won regardless.                                                                                                                                                                                          <m2>Kemar Roach, with his hat-trick</m2>                      0                     0                  []                      0                   []              0           []
1857            26    Sri Lanka      Zimbabwe     Sri Lanka   505135_23                                          The 116-run stand between Brendan Taylor and Regis Chakabva is the highest opening stand for Zimbabwe against Sri Lanka                                          The 116-run stand between Brendan Taylor and Regis Chakabva is the highest opening stand for Zimbabwe against Sri Lanka                                                   The 116-run stand between <<C2P31>> and <<C2P153>> is the highest opening stand for <<C2>> against <<C1>>              2                  0              2                  0                      1                                        <m23>The 116-run stand between Brendan Taylor and Regis Chakabva is the highest opening stand for Zimbabwe against Sri Lanka</m23>                                                                                                                                                                          It is also their highest total against Zimbabwe in ODIs.                      0                     0                  []                      0                   []              0           []
1504            21      England  South Africa       England   504435_37                                                                                                                                            England's six-run win                                                                                                                                            England's six-run win                                                                                           

In [281]:
print('Mention text has player pronoun but no player name: %s'%train_data1[(train_data1['count_players']==0) & (train_data1['player_pronoun_count']>0)][col_order].shape[0])
print('Mention text has player pronoun but no player name but context has: %s'%train_data1[(train_data1['count_players']==0) & (train_data1['add_count_players']>0) & (train_data1['player_pronoun_count']>0)][col_order].shape[0])
print('Mention text has country pronoun but no county name: %s'%train_data1[(train_data1['count_country']==0) & (train_data1['country_pronoun_count']>0)][col_order].shape[0])
print('Mention text has country pronoun but no county name but context has: %s'%train_data1[(train_data1['count_country']==0) & (train_data1['add_count_country']>0) & (train_data1['country_pronoun_count']>0)][col_order].shape[0])

Mention text has player pronoun but no player name: 166
Mention text has player pronoun but no player name but context has: 104
Mention text has country pronoun but no county name: 42
Mention text has country pronoun but no county name but context has: 21


#### Example Mention Text: has player pronoun but not player name

In [293]:
#print('Example Mention Text: has player pronoun but not player name. ')
col_order=['mention_key', 'mention_text','article_mention_line','article_mention_previous_line','count_players','add_count_players',
           'player_pronoun_count','player_pronoun_list']
print_full(train_data1[(train_data1['count_players']==0) & (train_data1['player_pronoun_count']>0)][col_order].head(5))

mention_key                                                    mention_text                                                                                                                                                                                                                                         article_mention_line                                                                                                                                               article_mention_previous_line  count_players  add_count_players  player_pronoun_count player_pronoun_list
13   501845_14                                        he conceded 69 off seven                                                                                                                                                                                        His day would not get better and <m14>he conceded 69 off seven</m14>.                     Shafiul Islam had given Sehwag too much width, and <m13>in his second over he strayed twice on to Sachin Tendulkar's pads</m13> with dire consequences.              0                  3                     1                [he]
24   501845_25                                        He fell in the 48th over                                                                                                                                                                                                                         <m25>He fell in the 48th over</m25>,                                                                  At one stage Sehwag, who had Gambhir running for him because of an injury, had a shot at a double-century.              0                  2                     1                [he]
31    501976_1                              this time he lasted 134 balls more                                                         The biggest difference was Virender Sehwag's performance: in that Trinidad game he scored 2 off 6; <m1>this time he lasted 134 balls more</m1>, and, not surprisingly, that made all the difference.                                          Right from the toss - India had chosen to bat on that occasion - almost everything was completely different between the two games.              0                  1                     1                [he]
36    501976_6                         He faced 140 deliveries in this innings                                                                                                             <m6>He faced 140 deliveries in this innings</m6>, which is the most he has ever faced in an ODI innings, beating his earlier record by one ball.  Before the tournament Sehwag spoke about his desire to bat for longer periods, and the manner in which he batted here showed he is serious about implementing those plans.              0                  1                     1                [he]
37    501976_7  he started off in a frenzy, scoring 12 off his first six balls  The way he paced his innings was interesting: <m7>he started off in a frenzy, scoring 12 off his first six balls</m7>, but then <m8>made only 15 off his next 27</m8>, so that <m9>after the first ten overs he was on a relatively subdued 27 off 33</m9>.                                       In fact, in 223 ODI innings, he has faced more than 120 deliveries only three times, and both the earlier instances were before 2004.              0                  0                     2           [he, his]

#### Example Mention Text: has country pronoun but not country name

In [294]:
#print('Example Mention Text: has country pronoun but not country name.')
col_order=['mention_key', 'mention_text','article_mention_line','article_mention_previous_line','count_country','add_count_country', 
           'country_pronoun_count','country_pronoun_list']
print_full(train_data1[(train_data1['count_country']==0) & (train_data1['add_count_country']>0) & (train_data1['country_pronoun_count']>0)][col_order].head(5))

mention_key                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         mention_text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      article_mention_line                                                                                                                                                                            article_mention_previous_line  count_country  add_count_country  country_pronoun_count country_pronoun_list
27    501845_28                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   They were 51 for 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <m28>They were 51 for 0</m28>.                                                    <m27>Kayes edged, flicked, pulled and drove him for boundaries, and a wayward wide contributed to Bangladesh taking 24 runs off the fifth over</m27>.              0                  1                      1               [they]
96    502044_13                                                                                                                                                                                                                                                                                                                                                                                                                                                              They had cobbled together just 14 runs - all in singles                                                                                                                                                                                                                                                                                                                                                          <m13>They had cobbled together just 14 runs - all insingles</m13> - when <m14>Southee nipped one off the seam to strike Alex Obanda in front of leg stump</m14>.                                    The new ball barely deviated off the straight for Southee but Kenya's young opening pair, perhaps over-awed by the occasion, remained nervously rooted to the crease.              0                  1                      1               [they]
330    502832_6                                                                                   

<div class="alert alert-block alert-info">
  
- As we see from there is some value in getting the extra context from article
- As of now we are relying on string based player names lookup for identifying player names
- Some more cases can be identified if we also include NLP based NER name entities identification
- If required, we can also include NLP based co-reference resolution for player names. 
</div>